### ISSUE TITLE
update type of "must be positive" variables?

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1106]
I reckon this variables should be `uint`, even if they must be also > 0.

```
include/notcurses/notcurses.h
1035:  int rows;         // number of rows, must be positive
1036:  int cols;         // number of columns, must be positive
2868:  int sectioncount;                // must be positive

python/src/notcurses/build_notcurses.py
82:  int rows;         // number of rows, must be positive
83:  int cols;         // number of columns, must be positive
306:  int sectioncount;         // must be positive

doc/man/man3/notcurses_plane.3.md
22:  int rows;         // number of rows, must be positive
23:  int cols;         // number of columns, must be positive

doc/man/man3/notcurses_menu.3.md
33:  int sectioncount;         // must be positive

USAGE.md
657:  int rows;         // number of rows, must be positive
658:  int cols;         // number of columns, must be positive

src/lib/internal.h
209:  int sectioncount;         // must be positive
```

**Comment by dankamongmen** [comment]
Certainly the documentation ought match the reality; I assume that this is the case in all the instances you've mentioned.

Where these are members of options structs, they probably should indeed be unsigned...though it's nice to have the option of using -1 as a sentinel somewhere down the road...I kind of prefer ints here because that way a coder error can (in some cases) be cleanly detected by checking against 0 (as opposed to UINT_MAX/2).

int to unsigned is in practice probably not an ABI break, though in theory it is (there's no guarantee that int and unsigned are the same size, but they usually are).

I feel no great urge to change these, but also have no great reason not to. If it's causing you difficulties, I can. If you think they're grossly incongruous with other code, I also can.

**Comment by joseluis** [comment]
> Where these are members of options structs, they probably should indeed be unsigned...though it's nice to have the option of using -1 as a sentinel somewhere down the road...I kind of prefer ints here because that way a coder error can (in some cases) be cleanly detected by checking against 0 (as opposed to UINT_MAX/2).

Ok I understand. We can leave them like that, it's not bothering me in any practical sense.

**Comment by joseluis** [comment]
Reopening because there are some clear cases where it should definitely be changed.

Specifically the `rows` and `cols` parameters in `ncplane_dim_yx` and `ncplane_dim_yx` should be `c_uint`.

**Comment by dankamongmen** [comment]
> Reopening because there are some clear cases where it should definitely be changed.
> 
> Specifically the `rows` and `cols` parameters in `ncplane_dim_yx` and `ncplane_dim_yx` should be `c_uint`.

do you refer to the rust or the c?

i agree that these ought have been `unsigned*`, but i am hesitant to change them now. while this would have no real effect on the ABI, the API would definitely change, and it would break working code.

in rust, feel absolutely free and encouraged to change them. whether or not you want to catch and reject incoming values that are greater than `INT_MAX` is your own business.

**Comment by dankamongmen** [comment]
> i agree that these ought have been `unsigned*`, but i am hesitant to change them now. while this would have no real effect on the ABI, the API would definitely change, and it would break working code.

after thinking about it a bit more, this would only break ABI if
 * we ever used negatives here (we don't), or
 * `int` and `unsigned` were different sizes (they're not), or
 * anything didn't use two's complement (they all do)

so yeah, i think we can change these up.

**Comment by dankamongmen** [comment]
hrmm, i started down this path, and there are a tremendous number of places where coordinates `can` be negative:

 * when translated from one plane to another
 * when describing a plane's origin, either absolutely or relative to another
 * when off-plane due to exhausting the visual range

so we definitely don't want `unsigned` everywhere we have a len/pos. if we want this in `ncplane_dim_yx()`, then, we'll need an internal cast. i suppose that's ok.

**Comment by dankamongmen** [comment]
I've started this experimental work in `dankamongmen/unsigned-dims`. Thus far, it's a surprising amount of churn.

**Comment by dankamongmen** [comment]
Given that almost every Notcurses program calls `notcurses_stddim_yx()` if not several more, and given the rules on C pointers, we're going to introduce a loud warning to pretty much every working program out there. This just might not be doable.

**Comment by dankamongmen** [comment]
ok yeah @joseluis i just spent about three hours messing with this. the many-hundred-LoC branch mentioned above is the result. it's nowhere near done -- we're positively lousy with compiler warnings everywhere. the fundamental problem is this:

* offsets are true ints, logically, and
* dimensions are unsigned ints, logically, but
* a great many offset computations are based off dimensions, and
* `ncplane_dim_yx()` is used extensively *within* the code as well as *without*, and
* mixing ints and unsigned ints in these computations generates warnings, unless
* i cast unsigneds down to ints all the time, rather defeating the purpose, and being terribly unsafe besides

so, alas, this just isn't happening, i don't think. take a look at that branch and tell me if you feel differently. sorry!

**Comment by dankamongmen** [comment]
Yeah, can't do it under the current arrangements. Closing as NONFIX =[.
