### ISSUE TITLE
confusing description about [ BI]PREFIXCOLUMNS

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1107]
from `notcurses.h`:

```c
// The number of columns is one fewer, as the STRLEN expressions must leave
// an extra byte open in case 'µ' (U+00B5, 0xC2 0xB5) shows up. PREFIXCOLUMNS
// is the maximum number of columns used by a mult == 1000 (standard)
// ncmetric() call. IPREFIXCOLUMNS is the maximum number of columns used by a
// mult == 1024 (digital information) ncmetric(). BPREFIXSTRLEN is the maximum
// number of columns used by a mult == 1024 call making use of the 'i' suffix.
// This is the true number of columns; to set up a printf()-style maximum
// field width, you should use [IB]PREFIXFMT (see below).
#define PREFIXCOLUMNS 7
#define IPREFIXCOLUMNS 8
#define BPREFIXCOLUMNS 9
```
I find the comments confusing, and I'm not sure if there's something wrong there.

1. Where it says PREFIXCOLUMNS shouldn't it say BPREFIXCOLUMNS?
2. Where it says `This is the true number of columns` is it referring to PREFIXCOLUMNS? If so it should be a separate paragraph from the above.
3. I don't get the part where it says `making use if the 'i' suffix, referring to **B**PREFIXSTRLEN. I feel like the description of the B & I prefixes are mixed up...

**Comment by dankamongmen** [comment]
agreed

**Comment by dankamongmen** [comment]
> 1. Where it says PREFIXCOLUMNS shouldn't it say BPREFIXCOLUMNS?

I only see PREFIXCOLUMNS once, and it seems correct (maximum number of columns used in a standard call).

> 2. Where it says `This is the true number of columns` is it referring to PREFIXCOLUMNS? If so it should be a separate paragraph from the above.

It's referring to the three different cases. [IB]PREFIXCOLUMNS is the true number of columns used for the three different cases.


> 3. I don't get the part where it says `making use if the 'i' suffix, referring to **B**PREFIXSTRLEN. I feel like the description of the B & I prefixes are mixed up...

It's not, but this paragraph is indeed a dumpster fire.

With base 1000, you can have xxx.yyU where U is unit. alternatively you can have say xx.yyyU. but you can't have xxx.yyyU. so 7 is the max.

With base 1024, you can have xxxx.yyU or xxx.yyyU, but you can't have xxxx.yyyU. so max is 8. alternatively you could have 1000 with a suffix for xxx.yyUs, where s is the suffix.

With base 1024 and a suffix (the largest form supported), you can have xxxx.yyUs.

I understand your pain, as I always have to go look at this to figure it out whenever I want to use it :(.

This is made more fun because the max number of columns is **not** equal to the max number of bytes because i had to get cute and use µ for micro instead of u. µ is utf8-encoded to two bytes.

I would get rid of this function if it wasn't so goddamn useful.

I welcome a PR. Otherwise, I'll try to do something better here.

**Comment by dankamongmen** [comment]
Any thoughts?

**Comment by dankamongmen** [comment]
This might be a case where it's difficult to provide sufficient concise documentation in the header file, and I ought instead simply point users at the `notcurses_metric(3)` man page: https://notcurses.com/notcurses_metric.3.html

**Comment by dankamongmen** [comment]
I've fleshed out the manual page a bit, and added a reference to it. PTAL and let me know if this is sufficient.
