### ISSUE TITLE
reset color after each line in ncdirect mode

### ISSUE THREAD

**Issue by kusky3** [dankamongmen/notcurses#1222]
I'd like to replace chafa & co. since ncls is 130% faster but:
- `ncls` has no `-q|--quiet` flag and requires piping to `tail -n+2` but the output is still not usable with `paste`
- `notcurses-view -q` waits for user input and adds "press key to advance"

**Comment by dankamongmen** [comment]
> I'd like to replace chafa & co. since ncls is 130% faster

YASSSSSSSSSSSSSSS

> ncls has no -q|--quiet flag and requires piping to tail -n+2 but the output is still not usable with paste
> notcurses-view -q waits for user input and adds "press key to advance"

I can add these, no problem. Can you specify exactly what behavior you're looking for? I.e., "when i supply this argument, i'd like to see the following thing happen."

I'm grokking that you want `notcurses-view` not to prompt for input. I was considering doing that for `-q`, but then I'm unsure what to do with multiple command line arguments (we'd just blow through them, leaving only the last one up). I can maybe make `-q` not prompt when supplied only one argument, or alternatively add a new flag to never prompt. I'm inclined to go with the first, as I see no possible application of the second.

As for the first thing (`ncls)`, I'm just entirely unsure what you want =].

let me know, and i'll get these in ASAP, so they're available in 2.1.2.

**Comment by kusky3** [comment]
i'm not asking for new features. i'm just having truoble trying to get a "clean" output from either notcurses-view or ncls that can be used in scripts.

**Comment by dankamongmen** [comment]
"new features" is just a term. bug, extension, feature, etc.

"used in scripts"...i've run both in scripts. it looks like you're looking for something that can be sent through `paste` or even `cat` at a different line length? so you just want a newline at the end of each line? like, i can `ncls file > e` and then `cat e`, just it looks weird if i change the terminal geometry. you want one that will work for all (as long or longer) terminal geometries? sorry for not understanding you immediately.

`^[[0m` is just reset graphical presentation, i believe.

**Comment by kusky3** [comment]
i might end up writing on my own a replacement for chafa with notcurses since ncls and notcurses-view have a different a scope and adding a special "-o|--output" just for my personal wants is probably harmful to this project.

**Comment by kusky3** [comment]
yes the ^[[0m prevents the description.txt from getting the same colour as the last image sequence
with ncls the description ends up coloured.

**Comment by dankamongmen** [comment]
ok so we need the `^[[0m` to reset the color in paste (i write one only at the end); that makes sense. i think we need a newline to make it work when you change the screen geometry. i'm just worried that this will cause skips in the normal mode of operation. let me play around with it. the `^[[0m` i can do now, easily.

**Comment by kusky3** [comment]
sorry i misclicked :D

**Comment by dankamongmen** [comment]
I still want to do the `^[[0m` =] and try to make it work on a geometry change.

if you want a fullscreen one, i'm thinking i might make `-k -q` work together to avoid the prompt in `notcurses-view`.

**Comment by kusky3** [comment]
i'm currently trying to replace chafa [here](github.com/kusky3/bookmenu)

**Comment by dankamongmen** [comment]
I've filed #1229 regarding `notcurses-view`, and I think this solution might be optimal for you. Either way, I'll get to both of these.

**Comment by kusky3** [comment]
> it looks like you're looking for something that can be sent through `paste`

exactly, and the two issue i'm having are:
- missing reset ^[[0m
- ncls occupies the entire height and notcurses-view -m is difficult to used because it requires an input and has the "press key" label

**Comment by dankamongmen** [comment]
i can do all that. when you say "ncls occupies the entire height", i'm not certain what you mean. It ought occupy either the entire height of the screen or the entire width, depending on the image geometry. I've been thinking of adding an option `--scale` allowing you to provide`none`, `scale` (the current), or `stretch` (occupy full screen). Would that help? The problem is that for "large" images (anything wider than 2x terminal columns), you pretty much have to scale the image for it to be visible. What in that case ought we scale to?

An example of an input and what you'd like to see happen would be useful.

**Comment by kusky3** [comment]
> when you say "ncls occupies the entire height", i'm not certain what you mean.
i pointed that out because when you ncls image.jpg > ncls.out and then cat ncls.out you actually lose 2 or 3 rows of the image

**Comment by dankamongmen** [comment]
I've put in the newlines. We now work across a geometry change.

**Comment by dankamongmen** [comment]
![2020-12-17-182409_3440x1420_scrot](https://user-images.githubusercontent.com/143473/102555593-14e83880-4095-11eb-9b05-aa1da233e11f.png)

i can't do anything about things looking shitty if you render to larger geometry, and then shrink the geometry, but this works for bigger geometries, and resets the color at line's end as requested.

**Comment by kusky3** [comment]
> trying to get a "clean" output from either notcurses-view or ncls that can be used in scripts.

i just realized i should be creating TUIs in C and not bash 🤦. I wouldnt be bothering you.

**Comment by dankamongmen** [comment]
OK, so we covered a number of things in this issue:

* Preserve color/style in `ncdirect_render_image()` at end of each line.
  * This is done, except we're returning to *default* color, rather than *previous*. See #1230.
  * This *will not* take effect in `notcurses-demo`, which uses fullscreen mode
* Newline following each line of `ncdirect_render_image()` output
  * Added. This works, surprisingly, even when we use the full width.
  * This *will not* take effect in `notcurses-demo`, which uses fullscreen mode
* `ncls` sometimes uses the full height, which gets scrolled off the screen
  * I see no good solution for this within notcurses. Try using `read -s` together with your display, I guess?
  * If you can use C, just output, and then wait for input, easy peasy
* `notcurses-view` needs a mode that doesn't prompt
  * see #1229 

i expect #1229 and #1230 to be done before 2.1.2 is released.

does this give you everything you need? if so, please mark this issue closed. =]

**Comment by dankamongmen** [comment]
> i just realized i should be creating TUIs in C and not bash . I wouldnt be bothering you.

fuck that, you've provided extremely valuable feedback; thank you!

**Comment by kusky3** [comment]
> does this give you everything you need? if so, please mark this issue closed. =]

wow, more than i could wish
