### ISSUE TITLE
ncdirect style setters ought match ncplane

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1247]
They are documented as `ncplane_styles_*() analogues`, but those analogs are deprecated. Shouldn't be the ndirect styles API  change too?

**Comment by joseluis** [comment]
Also, there doesn't seem to be a way to get the current styling. Is that by design?

**Comment by dankamongmen** [comment]
1) the `ncplane_styles_*()` functions were deprecated because `ncplane_set/on/off_styles()` were introduced, matching the remainder of the `ncplane_set_*()` functions. we don't have that formation in `ncdirect`, so there's no point in renaming them. so i understand, anyway.

2) nope, i'll add it!

**Comment by dankamongmen** [comment]
Indeed, it is exactly this lack of functionality that gives rise to the lack of `ncplane`-like naming. We might have to do some renaming and deprecating here. We'll see.

**Comment by joseluis** [comment]
I just don't like having to call `ncplane_set_styles` on one case and `ncdirect_styles_set` on another for the same contextual operation. Irregularities like that add more cognitive weight.

**Comment by dankamongmen** [comment]
> I just don't like having to call `ncplane_set_styles` on one case and `ncdirect_styles_set` on another for the same contextual operation. Irregularities like that add more cognitive weight.

I agree with you. I don't believe there to be many clients of direct mode in the wild, so I'm less worried about backwards compatibility there..,it's still bad form, though. Let me see what exactly needs to change.

**Comment by dankamongmen** [comment]
I've deprecated `ncplane_styles_{set, on, off}` in favor of `ncplane_{set, on, off}_styles` to match the `ncplane_` equivalents. This will be present in 2.1.3.

**Comment by dankamongmen** [comment]
As for getters...we'd have the choice of either:

* introducing them and having a different naming scheme than ncplane, again, or
* a substantial break of ABI compat

**Comment by joseluis** [comment]
It's not late for breaking things, I think, how much is notcurses really used right now? Do you have any metrics?

**Comment by dankamongmen** [comment]
> It's not late for breaking things, I think, how much is notcurses really used right now? Do you have any metrics?

twice now i have assumed no one was using something, and found out when angry european maintainers mailed me asking whether my feckless attitude regarding ABI compatibility was somehow due to America's broken health care system and if it was our failed schools' fault that i'd never bothered to learn how to use computers

**Comment by dankamongmen** [comment]
> > It's not late for breaking things, I think, how much is notcurses really used right now? Do you have any metrics?
> 
> twice now i have assumed no one was using something, and found out when angry european maintainers mailed me asking whether my feckless attitude regarding ABI compatibility was somehow due to America's broken health care system and if it was our failed schools' fault that i'd never bothered to learn how to use computers

this makes me realize maybe we should go ahead and change it, if only to irritate europeans

**Comment by dankamongmen** [comment]
I think the reasons I originally didn't bother to provide style accessors for ncdirect were:

* we can't be sure of the current styling anyway, since ncdirect admits arbitrary other output to the same sinks, and someone could have emitted arbitrary escapes (consider someone running a subprocess, which freely changes the color). to do this properly, it would need to be some kind of console read, which i really seek to avoid (if it even exists)
* it makes sense to need to discover the styling of a plane when you've got a bunch of planes -- that's their entire purpose, to serve as a data structure. you only have one plane in ncdirect. if you have to ask what the color is, what guarantees you'll remember it to the next line? soon you're a doddering fool, asking over and over "what color is it?", perhaps while wearing an onion on your belt, which was the style at the time

we'll have to find another way to vex the Continentalists, alas.



https://user-images.githubusercontent.com/143473/103204765-0b957200-48c6-11eb-93ce-4bf71589501d.mov

**Comment by dankamongmen** [comment]
they didn't have white onions, because of the war
