### ISSUE TITLE
fallin' demo breaks when run atop sexblitter-drawn background on glibc 2.31

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1274]
This requires:

* running a terminal which uses sexblitter (VTE, Kitty),
* running `fallin'` following a demo which uses a sextant background (`luigi` works),  and
* a libc lacking Unicode 13 support (e.g. Debian Unstable's 2.31)

`fallin'` reads the background character (a sextant), then tries to put it through `cell_prime()`. This fails, because older `wcwidth()` returns -1 for Unicode 13 characters (we work around this in the sexblitter via direct blitting, which isn't exposed beyond the library core).

This doesn't happen with the actual Debian/Fedora release, because `luigi` is disabled in DFSG builds. But check out head, build it locally, and run the default demo, and it'll happen.

**Comment by dankamongmen** [comment]
I very much do *not* want to expose `pool_blit_direct()` or even `cell_load_direct()` to the user. This isn't a fault of the Notcurses API; it's a fault of glibc. Maybe we introduce a `wcwidth()` shim that handles sextants in the `wcwidth()` error path? Yuck, but it would work...for sextants, anyway, not other Unicode 13 characters :/.

**Comment by dankamongmen** [comment]
So this has only been broken since 2.1.2, thankfully.

**Comment by dankamongmen** [comment]
I think introducing internal `ncwidth()` is the cleanest way to handle this.

**Comment by dankamongmen** [comment]
That fixes it.

**Comment by kovidgoyal** [comment]
Just FYI, wcwidth() is fundamentally broken. You cannot compute the number of cells a string will take using wcwidth(). You have to use wcswidth(). This is because of things like emoji presentation mode variation selectors. Combining flag codepoints, skin tone modifiers, etc. 

Furthermore, relying on the system wcswidth() is not going to work. It means the width of strings now depends on what system they are running on. You get different results as you ssh into different systems. You are better of having your own wcswidth() implementation that is generated directly from the unicode standard. While the unicode standard does occasionally change the idth of characters, this is relatively rare, mush rarer than sshing into systems with different versions of glibc. This is fairly easy to do, there is a script to do it in the kitty source code, see gen-wcwidth.py.

If you are interested, we could collaborate on splitting that into its own package. This has been on my TODO list forever, however, never gotten around to it, since I personally have no use for splitting it, it just makes more work for me.

**Comment by dankamongmen** [comment]
yeah i'm familiar with the many shortcomings of `wcwidth()` :(. i'm not sure i have the bandwidth to go down that road very far (it's been discussed here a few times), but i might get back to you on it.

**Comment by dankamongmen** [comment]
i was not aware, however, that `wcswidth()` is more accurate than a sum over `wcwidth()`  (it makes sense that it could be, of course, i just doubted glibc actually had any improvements there--i thought all the combining logic was in the text layout engine e.g. harfbuzz. i'm pretty ignorant of that layer). that's good to know thanks @kovidgoyal .

i think i'd not bothered to look into that because if, say, someone laid down EGCs that would combine as distinct entitites, i didn't want to have to do a context-sensitive `wcswidth()` across, what, the entire line? i'm still unsure how exactly to deal with that problem, which i don't think i've made very clear here, ugh.

**Comment by kovidgoyal** [comment]
You dont need harfbuzz/text layout for this (ignoring the question of non-monospaced text, for which the whole concept of width in cells is anyway undefined). Codepoint combining rules are specified in the unicode standard. 

I dont quite understand the problem you have described. Generally with text strings when rendering to a terminal what one needs to do is split the text into sections of some given width. So you start at the beginning and split as you go.
