### ISSUE TITLE
'Squares' appearing in output of notcurses-view

### ISSUE THREAD

**Issue by MaxBarraclough** [dankamongmen/notcurses#1298]
On the server side I'm running Ubuntu 20.10/AMD64. On the client side I'm running PuTTY 0.74 on Windows 10.

Test image: https://wikilovesmonuments.org.uk/wp-content/uploads/2020/11/Perch_Rock_Lighthouse_in_rock_pool.jpg

Below are screenshots from `COLORTERM=24bit notcurses-view ~/Perch_Rock_Lighthouse_in_rock_pool.jpg`, and then the output from an alternative program, [imcat](https://github.com/stolk/imcat), with command `~/stolk-imcat/imcat             ~/Perch_Rock_Lighthouse_in_rock_pool.jpg`.

The output from notcurses-view doesn't look as good, as it shows what look like squares in some of the cells.

![notcurses-view_output](https://user-images.githubusercontent.com/1122128/104921164-de9e2180-5990-11eb-9b92-52689ceb2036.png)
![imcat_output](https://user-images.githubusercontent.com/1122128/104921173-e1991200-5990-11eb-953e-75e5a9cf0042.png)

**Comment by dankamongmen** [comment]
I am guessing from first look that this is due to PuTTY not rendering quadrants as well as it could. In `notcurses-view`, you can change the current blitter by using the digits. The blitter being used is shown in the upper left corner -- here we see that "quadblitter" is in use. The available relevant blitters are "ascii", "halfblitter", "quadblitter", and "sexblitter". Would you try pressing '2' to use the halfblitter (I believe this is the same technique used by `imcat`), and let me know how it looks? We might have to prevent PuTTY from using the quadblitter.

Thanks so much for this excellent bug report! All I can promise is that I will take every report seriously, and investigate it to its end.

**Comment by dankamongmen** [comment]
What font are you using? I'm able to view with `quadblitter`, and it looks reasonable. My putty font is set to "server:fixed", and `fc-match` reports for `fixed`:

```
[schwarzgerat](0) $ fc-match fixed
7x13-ISO8859-1.pcf.gz: "Fixed" "Regular"
[schwarzgerat](0) $ 
```

If I switch to `Hack`, drawing looks like garbage. some terminals draw the block characters themselves, and this is usually the best thing to do. some use font glyphs, and this obviously depends on your font. what info can you provide? thanks!

**Comment by dankamongmen** [comment]
Here's what I see in a 94x70 `xfce4-terminal` using `Liberation Mono Regular 10` (again, the font isn't used for the blocks, just for the size) in `ncplayer` (recently renamed from `notcurses-view`) using three different blitters:

halfblock:
![2021-01-19-050558_942x1417_scrot](https://user-images.githubusercontent.com/143473/105019417-0edad400-5a14-11eb-8fa4-2c67a6b4ac1c.png)

quadblitter:
![2021-01-19-050603_942x1417_scrot](https://user-images.githubusercontent.com/143473/105019450-17330f00-5a14-11eb-97ad-7d181f126c84.png)

sexblitter:
![2021-01-19-050610_942x1417_scrot](https://user-images.githubusercontent.com/143473/105019462-1b5f2c80-5a14-11eb-9758-f1b4c4b0d82b.png)

**Comment by dankamongmen** [comment]
here's `imcat` in the same situation
![2021-01-19-050820_942x1417_scrot](https://user-images.githubusercontent.com/143473/105019694-5bbeaa80-5a14-11eb-8410-f5f7b09f35ec.png)

**Comment by dankamongmen** [comment]
i can't help but notice that `ncplayer` is *significantly* faster =]

**Comment by MaxBarraclough** [comment]
Looks like xfce4-terminal renders it better than PuTTY. Here are some more screenshots from `ncplayer` on Ubuntu 20.10/AArch64, viewed over PuTTY 0.74 on Windows 10.

Default blitter (quadblitter), font: `terminal`, size 14:

![1-terminal](https://user-images.githubusercontent.com/1122128/105052757-28a60680-5a68-11eb-835d-e6081116070e.png)

--------------------------------

Default blitter (quadblitter), font: `fixedsys`, size 14:

![2-fixedsys](https://user-images.githubusercontent.com/1122128/105052771-2ba0f700-5a68-11eb-8728-febbf3d623b5.png)

--------------------------------

Default blitter (quadblitter), font: `courier`, size 14:

![3-courier](https://user-images.githubusercontent.com/1122128/105052787-2e9be780-5a68-11eb-90db-72747252fb52.png)

--------------------------------

Default blitter (quadblitter), font: `consolas`, size 14:

![4-consolas](https://user-images.githubusercontent.com/1122128/105052801-322f6e80-5a68-11eb-8184-f07a35a72b5b.png)

--------------------------------

ascii blitter, font: `couriernew`, size 14:

![5-couriernew-ascii](https://user-images.githubusercontent.com/1122128/105052811-352a5f00-5a68-11eb-9c8f-8edeb6855097.png)

--------------------------------

halfblock blitter, font: `couriernew`, size 14:

![6-couriernew-halfblock](https://user-images.githubusercontent.com/1122128/105052821-38254f80-5a68-11eb-9b39-72b78c9748fe.png)

--------------------------------

sexblitter, font: `couriernew`, size 14:

![7-couriernew-sexblitter](https://user-images.githubusercontent.com/1122128/105052836-39ef1300-5a68-11eb-9ea2-32ba3432df16.png)

**Comment by dankamongmen** [comment]
i get a similar effect in XTerm when i *do not* use TrueType fonts, and instead use `fixed`. I wonder if the two are related?

![2021-03-22-004259_952x1057_scrot](https://user-images.githubusercontent.com/143473/111941559-aeb1ee00-8aa7-11eb-916c-81c4577d6091.png)

**Comment by dankamongmen** [comment]
Hey there @MaxBarraclough , sorry for ignoring this bug for so long.

What does it look like in your `putty` setup if you try running `ncplayer -bascii` on the same image? What about `ncplayer -bhalf`? You can switch between blitters using the number keys 1..6; does anything look good for you? You could also try `notcurses-demo -p ../data k` to run the `keller` demo, which tries each blitter while identifying the blitter being used. Are there any good results?

**Comment by dankamongmen** [comment]
It's possible that the commit I just made, present in the 2.2.6 release, will resolve this problem for you, as it will only use quadrants for whitelisted values of `TERM`. putty is not one of these, so let's see what happens.

**Comment by dankamongmen** [comment]
hey @MaxBarraclough , have you been able to see whether or not things have improved since 2.2.6? so long as halfblocks display correctly, you ought now be getting non-broken output.

**Comment by MaxBarraclough** [comment]
@dankamongmen Thanks Nick I've not yet had a chance to confirm, I'll get back to you when I'm able.

**Comment by dankamongmen** [comment]
> @dankamongmen Thanks Nick I've not yet had a chance to confirm, I'll get back to you when I'm able.

thanks a lot mang!

**Comment by dankamongmen** [comment]
ok i got a putty and windows environment to play with. windows 11, putty 0.76 (btw, it looks like we can identify putty via a raw ^E aka 0x05; it returns "PuTTY" by default). i can confirm that putty using its default fonts does not support a good quadblitter or sexblitter; thankfully, we've turned both of those off (as explained above). so that ought eliminate our "squares", and indeed it does seem to do so (Courier New 10). `Consolas 10` looks similarly deprived.

HOWEVER, if i change to `Cascadia Code 10`, i get working quadblitter glyphs (and much better emoji).

so ideally i would detect the font and see if it was a known-working one, maybe. but for now i'll just recommend `Cascadia Mono 10 Regular`, though you still won't be able to get quadblitter with it. even then, some stuff looks pretty decent.

i'm going to go ahead and call this closed. feel free to reopen, or to open new issues.
