### ISSUE TITLE
consider supporting the jexer bitmap protocol

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1530]
the illustrious @klamonte speced out something interesting, and implemented it in jexer:

https://gitlab.com/klamonte/jexer/-/wikis/jexer-images

no one else seems to be supporting it, per se, but why would they if no one's emitting it? might as well.

**Comment by dankamongmen** [comment]
(noticed this in the ayosec/graphics sixel bug)

**Comment by dankamongmen** [comment]
i don't think we'll be adding any more bitmap backends for kicks. it's quite enough work dealing with the four we have.

**Comment by klamonte** [comment]
For anyone coming it afterwards: **I agree on the merits of this decision.**  _(I also ask forgiveness for the presumption that I have standing to approve or disapprove of someone else's efforts on their own project and time.)_

I put the doc out because it was the smallest thing I could imagine that got "something like sixel, but 24-bit and not awful" across the wire, and to demonstrate the bare minimum: push bits and advertise just that one feature in DA1.  This was during the very long "simple image support" discussion that only resulted in: 1) mintty adopting iTerm2 support, and 2) no new spec making anyone happy enough to actually write code.

I did run it by Dickey for comment once, and nothing came out if it, e.g. it did not advance a goal for xterm or ncurses to adopt a non-sixel bitmap image format.  I suspect if one were to write and commit to supporting an xterm patch -- which would include adding a base64 decoder and potentially link to libjpeg/libpng/others -- it *might* get included upstream as an optional feature.  But maybe not.  But as soon as something is adopted by xterm or ncurses, I will be pointing people that way.

**Comment by dankamongmen** [comment]
certainly if it's ever picked up, i'll implement it; as you note, it would likely be merely an augmentation of our existing sixel backend.

as for terminal bitmap graphics, i hope that kitty's protocol is picked up by more terminals.
