### ISSUE TITLE
same ncvisual rendered multiple times only shows the last time

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1548]
from: https://github.com/dankamongmen/notcurses/discussions/1488#discussioncomment-624828

Example in rust showing the problem: [pixel-cell](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/pixel-cell.rs#L40-L64)

**Comment by dankamongmen** [comment]
Hijo de las mil putas, gigaputas even

**Comment by dankamongmen** [comment]
Ugh I don't want to add more crap to the 2.3.0 plate, but let's see how difficult this is, and tentatively look for it in 2.3.0.

**Comment by dankamongmen** [comment]
Looking at this for unrelated reasons, I see we have a single `struct sprixel* spx` associated with a given `ncvisual`, which certainly doesn't seem right. That ought probably live with the TAM in an `ncplane` -- it has to, actually, given cell wiping.

That's cool if we can extract it entirely from the `ncvisual`, though, because right now there are annoying lifetime/ownership issues involved with associating the sprixel with both `ncvisual` and `ncplane`. So that's a good thing. The only worry is that we don't want to rebuild the sprixel should we happen to render it to two different planes...but actually we would *need* to if any cells had been wiped. So this looks like just pre-wiping badthought. Let's pull it out of the `ncvisual`, and I bet that might fix this by itself.

**Comment by dankamongmen** [comment]
I've removed the sprixel reference from the `ncvisual`, and things seem to still be working...not yet sure that this will fix the issue, but it definitely can't hurt.

**Comment by dankamongmen** [comment]
I made a quick change to `pixels.c` to comment out the `ncplane_destroy()` each iteration, and as expected, I ended up with a screen full of WarMECHs. I think this will resolve your problem, also. Please confirm if you can, but marking this fixed on merge.

**Comment by joseluis** [comment]
The pixel-cell example now just works without any changes, showing both renderings of the visual :) thank you for the speedy fix!

**Comment by dankamongmen** [comment]
awesome, it has been a productive evening, woo-hah

[![big baby jesus, i can't wait](http://img.youtube.com/vi/6ItoVPAlHHU/0.jpg)](http://www.youtube.com/watch?v=6ItoVPAlHHU "i can't wait")
