### ISSUE TITLE
add NCSCALE_INFLATE

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1576]
as commented in https://github.com/dankamongmen/notcurses/issues/1546#issuecomment-821970244 so that we don't forget.

This would need a way to pass scaling information to ncvisual_options.

And [here](https://github.com/dankamongmen/notcurses/discussions/1488#discussioncomment-610788) you were talking about disabling the plane parameter from ncvisual_options. If that's still on it may be worth to do all these changes together.

**Comment by dankamongmen** [comment]
if the target plane is not integer multiples of the input graphic, ought i reject that, or ought i just do discontinuous inflation? at its most fundamental, i have an input graphic of two pixels: a red one, and a blue one to its right. i use `NCSCALE_INFLATE` together with `NCBLIT_1x1` to target a plane of 1 row and 3 columns. what ought be the result?

**Comment by joseluis** [comment]
>  i have an input graphic of two pixels: a red one, and a blue one to its right. i use `NCSCALE_INFLATE` together with `NCBLIT_1x1` to target a plane of 1 row and 3 columns. what ought be the result?

This is what gimp does, going from this 1x2 image:
![image](https://user-images.githubusercontent.com/5832068/115700352-e04bfc80-a366-11eb-99c5-5ae0700d7ce1.png)

scaled to 1x3 without interpolation
![image](https://user-images.githubusercontent.com/5832068/115700274-cb6f6900-a366-11eb-9f95-cb0d183fb85f.png)

scaled to 1x3 with interpolation
![image](https://user-images.githubusercontent.com/5832068/115700652-302ac380-a367-11eb-82c4-b2daf63fd33a.png)

**Comment by dankamongmen** [comment]
> > i have an input graphic of two pixels: a red one, and a blue one to its right. i use `NCSCALE_INFLATE` together with `NCBLIT_1x1` to target a plane of 1 row and 3 columns. what ought be the result?
> scaled to 1x3 without interpolation
> ![image](https://user-images.githubusercontent.com/5832068/115700274-cb6f6900-a366-11eb-9f95-cb0d183fb85f.png)

and this is acceptable to you, Master Pixel Artist? if so, no problem.

**Comment by joseluis** [comment]
This could be regarded as allowing stretching, with a bias from the end when filling odd measures... I think this is fine. The alternative would be not to allow stretching at all, since perfect symmetry is impossible. As long as the user makes sure to have the correct lengths for its use case there shouldn't be any problem.


> and this is acceptable to you, Master Pixel Artist?

It's Dr. Master Pixel Artist Senior Esquire Commander in Chief and Lord of the Beasts from the Land and Fishes from the Sea from Monday to Friday Free Delivery No questions asked to you.

**Comment by dankamongmen** [comment]
alright, i'm implementing this now in the `dankamongmen/inflate-scale` branch. let's get a rigorous spec:

* There will be a new `ncscale_e` member, `NCSCALE_INFLATE`. The purpose of this scaling method is to fit the visual to the target plane without using interpolation, while preserving aspect ratio. I do not see a purpose for `NCSCALE_INFLATE_HIRES` (this is supplied for `NONE` and `SCALE` to indicate willingness to sacrifice aspect ratio for higher resolution, i.e. use Quadblitter or Sexblitter over Halfblitter, if available).
* When used with `NCBLITTER_DEFAULT`, `NCSCALE_INFLATE` will result in `NCBLIT_2x1` (Halfblitter), decaying to `NCBLIT_1x1` if `NCBLIT_2x1` is not available.
* `ncscale_lex()` will now convert `inflate` to `NCSCALE_INFLATE`.
* `ncscale_to_string()` will now convert `NCSCALE_INFLATE` to `inflate`.
* When used without a target plane (i.e. creating a plane), `INFLATE` will solve for the new plane's geometry using the same method as `SCALE`, to preserve aspect ratio. With no `n`, this is relative to the viewing area; with a non-`NULL` `n` and `OPTIONS_CHILDPLANE`, this is relative to the provided `n`.
* When used with a target plane, `INFLATE` will use the same method as `SCALE`.
* It is, for now, an error to render with `NCSCALE_INFLATE` to a target smaller than the visual's natural render.
* Rather than using the multimedia layer's interpolative scaling, `NCSCALE_INFLATE` will use our non-interpolative scaling.
* If the target geometry is not an even multiple of the input geometry, inflate as evenly as possible.

Thoughts: maybe this ought be `NCSCALE_NONINTERPOLATIVE` rather than `NCSCALE_INFLATE`, in case we one day want to handle the deflation case?

Maybe those two things are orthogonal, and really we want our current scalings, but also a control on interpolation?

**Comment by dankamongmen** [comment]
let's get this for 3.0.1 if possible

**Comment by dankamongmen** [comment]
having pondered this a bit more, i think `NCSCALE_INFLATE` is the wrong way to go. what we're talking about here isn't a sizing property, but a scaling property. we ought be able to use non-interpolative scaling to any size (and now can, with `resize_bitmap()`); we ought reuse the existing apparatus for describing target size (`NCSCALE_STRETCH`, `leny`/`lenx`, etc.), and allow non-interpolative scaling to be selected along a distinct axis.

i'm thus going to remove `NCSCALE_INFLATE` (it wasn't implemented yet anyway), and add `NCVISUAL_OPTION_NONINTERPOLATIVE`. when this flag is used, any scaling in `ncviusal_blit()` will be performed with the common `resize_bitmap()` function rather than the engine-specific `*_resize_internal()` (introduced in #1725 for #1718). when there is no multimedia engine present, this will be the only kind of scaling available.

anyone see a problem with this?

**Comment by joseluis** [comment]
I like it. It does make sense. Also it sounds like this will be easier to implement. I'm eager to play with this.

**Comment by dankamongmen** [comment]
sweet, big things happening this weekend after two crushing weeks of the shit side of bipolar disorder. mania ahoy!!!!!!

**Comment by dankamongmen** [comment]
how are we going to make this available to direct mode? once again, we face the cold hard fact that failure to incorporate `ncvisual_options` into the Direct Mode API was a foolish, stupid mistake =[.

remember, direct mode cuts in at `ncvisual_blit()`, **not** `ncvisual_render()`. so if we want this taken care of in a unified way, we have to do it in `ncvisual_blit()` -- which was probably the best place anyway, but it's now forced.

so i guess we add it to `blitterargs` either as a `bool` or by reproducing the entire `flags` word. we've so far managed to keep that out of `blitterargs`, but maybe we ought just bite the bullet. that's becoming its own mess =[. done this way, direct mode can certainly get the `NCVISUAL_OPTION_NOINTERPOLATE` into the thick of things...but how does the user request it through the direct mode API?

if there's no multimedia engine, this is the only scaling available to us. so `ncvisual_blit()` is a good place to put this from that perspective, also.

**Comment by dankamongmen** [comment]
NICHOLAS YOU STUPID DUMB ASSHOLE WHY DIDN'T YOU MAKE `ncdirectf_render()` TAKE A `ncvisual_options` WHY DO YOU INSIST ON MAKING LIFE HARDER THAN IT IS

**Comment by dankamongmen** [comment]
i mean direct mode can always call `ncvisual_inflate()` with a `ncdirectf`, i guess.

**Comment by dankamongmen** [comment]
> i mean direct mode can always call `ncvisual_inflate()` with a `ncdirectf`, i guess.

no, `ncvisual_inflate()` is yet another example of brainded fifth factor retardedness, what with its wholesome positive integer argument and inability to think beyond squares, ugh, it's like a `resize_bitmap()` for ants

**Comment by dankamongmen** [comment]
alrightie, i think this is all done, putting up the PR
