### ISSUE TITLE
[sixel]: black lines covering the entire width of the screen

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#1611]
I'm seeing black lines covering the entire width of the screen in xray (in both foot and XTerm):

foot:
![sixel-black-lines](https://user-images.githubusercontent.com/14031526/116755995-a4223700-aa0b-11eb-9a0e-3d61603a1899.png)

XTerm:
![sixel-black-lines-xterm](https://user-images.githubusercontent.com/14031526/116756411-5823c200-aa0c-11eb-969d-ddf44717d19b.png)

It appears to depend on the terminal size, which I'm guessing means it depends on the sixel image size. And that probably means it's related to sixels being a multiple of 6?

> * `export | egrep 'LANG|LC_CTYPE|TERM'`

```
COLORTERM=truecolor
LANG=sv_SE.UTF-8
LC_CTYPE=en_US.UTF-8
TERM=foot
```

> * notcurses version (available from `notcurses-demo i`)

https://github.com/dankamongmen/notcurses/commit/7c530728032c16e3f8952e50482794a4da1cd98e (current master)

> * terminal name + version

* foot version: 1.7.2-75-g47c7665b (Apr 30 2021, branch 'master') +ime +pgo
* XTerm(367)

**Comment by dankamongmen** [comment]
I have seen these as well, and was kinda hoping they would go away without my involvement, lol. Thanks for filing a bug on them. I'll look into this, though I might not fix it for 2.3.0, depends on how mysterious the root cause is. Might have to do with #1560, which I'm going to (hopefully) get to today. Might be it'll fix this. Might not.

**Comment by dankamongmen** [comment]
@dnkl , i do not see this problem if i build against OIIO instead of ffmpeg. I'm  going to look into this a bit more; I think ffmpeg is also responsible for weird pseudo-borders i see in `chunli` and `keller`.

I have implemented a complete solution for #1560, and it had no effect on this. I think this is an effect of ffmpeg's scaling.

**Comment by dankamongmen** [comment]
it looks like those pixels are, for whatever reason, not #000000 coming out of libswscaler. =[

**Comment by dankamongmen** [comment]
i've been looking for a libav option to fix this up, but haven't found anything yet. i'm considering adding an ImageMagick dep to notcurses-core that would be used for resizing, and hopefully it would eliminate this? i don't know.

this problem goes away if i return to considering anything with an alpha less than 192 to be transparent in `ffmpeg_trans_p()`. the only problem with that is that we lose the ability to display anything that authentically has an alpha less than 192. i changed it due to such an image (see #1540).

**Comment by dankamongmen** [comment]
hrmmmm. it's looking possible that i might need to keep an alpha channel out of the output when rescaling an opaque image. i.e. RGB shouldn't go to RGBA when getting scaled in ffmpeg. i'm not yet sure of this, but it seems possible.

to do that, i'd need to identify picture formats having no alpha channel, and take them to RGB, *and* teach all the blitters to handle RGB. on the other hand, this does result in less unnecessary bandwidth consumption moving through notcurses (and potentially even out to the terminal). hrmm.

**Comment by dankamongmen** [comment]
hrmm, if i use `SWS_POINT`, we don't see this effect (though the scalings do look like complete shit otherwise). let me play around for a bit...

**Comment by dankamongmen** [comment]
`SWS_BICUBLIN` does have them, far more actually

**Comment by dankamongmen** [comment]
`SWS_BICUBIC` has less than `BICUBLIN` but more than `LANCZOS`. `SWS_BILINEAR_FAST` has just the hints of outlines, and no black lines, but looks only a little better than `SWS_POINT`. so it seems that the better the scaler you use, the more crap you have, until you hit `SWS_LANCZOS`, which gives you the best quality plus just a little bit of black and white lines.

so yeah i'm thinking to do this perfectly, i've got to use my high-grade scaler together with a non-alpha target channel. but wait no that doesn't work i need a target alpha channel here. =[

**Comment by dankamongmen** [comment]
i don't see these anymore. do you agree, @dnkl ?

**Comment by dankamongmen** [comment]
(and yeah, i think they were related to sixel multiple of 6 as well. all that stuff about mplayer above relates to another problem i'm seeing sometimes).

**Comment by dnkl** [comment]
Yeah, not seeing these anymore! Nice job, whatever it was that fixed it :)

**Comment by dankamongmen** [comment]
w00t! get your money for nothin' and the fix for free
