### ISSUE TITLE
use P2=0 to nuke regions from orbit

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1619]
See https://codeberg.org/dnkl/foot/issues/391#issuecomment-193689, which is fine reading. Explore the use of highly-compressed `P2=0` sixels as fast bitmap/glyph eliminators.

**Comment by dankamongmen** [comment]
Also, could this be used to clean up the artifacts currently left in XTerm when running `xray`? It seems possible! Probably just results in massive flicker and Thomas Dickey screaming through your speakers, though.

**Comment by dankamongmen** [comment]
wait, didn't i already look into this once? hrmmm.

**Comment by dankamongmen** [comment]
this could be an effective way to implement bitmap clearing for sixel on startup, like we provide for kitty.

**Comment by dnkl** [comment]
While I certainly understand why this might look very useful, I'm not so sure it actually is. I'm fairly confident that XTerm treats sixels as separate layers; "erase" in this context still means creating a **new** sixel, and layering it in top of the cell grid, and previously emitted sixels. I.e. all the old stuff is still there, you're just putting a blanket over it.

Foot works like this too, minus layering multiple sixels on top of each other. I guess you could say foot splices a second sixel into an existing sixel, at cell granularity, when you write a sixel on top of another). But sixels are still on a separate layer from the cell grid.

This is a fairly natural implementation. Mainly because sixels aren't necessarily aligned to cells. At least not their bottom and right sides.

Btw, completely unrelated, and just a wild guess - you have one or more codeberg notification emails in your spam folder...

**Comment by dankamongmen** [comment]
> While I certainly understand why this might look very useful, I'm not so sure it actually is. I'm fairly confident that XTerm treats sixels as separate layers; "erase" in this context still means creating a **new** sixel, and layering it in top of the cell grid, and previously emitted sixels. I.e. all the old stuff is still there, you're just putting a blanket over it.

we'll be knowing very soon, as i attempt to use this to clean up xray detritus. with that said, i assume your description here corresponds to foot's recent multigraphic work? and thus P2=0 will not work to destroy a sixel in one go?

**Comment by dankamongmen** [comment]
btw, for your amusement, i've started putting some content here: [STEGAP](https://nick-black.com/dankwiki/index.php?title=Spriteful_TErminal_GrAphics_Protocol)

**Comment by dnkl** [comment]
> with that said, i assume your description here corresponds to foot's recent multigraphic work? and thus P2=0 will not work to destroy a sixel in one go?

Foot, with the recent multigraphic work, is still different from XTerm. While XTerm keeps layering new images on top of each other, foot will merge them. I.e. there is never a "stack" of images. So, this will actually work out fairly well in foot I think. You won't be "destroying" any sixels though - just replacing one with another ("empty") one. And the text under is still there. But to the user, sure, it'll look like the screen has been erased.

There is likely going to be a drop in performance on the terminal side **after** the "erase", since it's typically more expensive to render a sixel (even if it's just a blank one) than the regular grid. Foot is currently rendering sixels single-threaded (while the text grid rendering is multi-threaded). Though https://codeberg.org/dnkl/foot/issues/468 will hopefully mitigate that.

Due to differences in the color handling related to _Set Raster Attributes_, you'll have to configure **both** sixel register `#0` (for XTerm and Alacritty), **and** set the current ANSI background color (for foot and mlterm). Unsure which variant the other terminals implement.

**Comment by dnkl** [comment]
> btw, for your amusement, i've started putting some content here: STEGAP

Cool! Will try to find some time to read it soon.

**Comment by dankamongmen** [comment]
> There is likely going to be a drop in performance on the terminal side **after** the "erase", since it's typically more expensive to render a sixel (even if it's just a blank one) than the regular grid. Foot is currently rendering sixels single-threaded (while the text grid rendering is multi-threaded). Though https://codeberg.org/dnkl/foot/issues/468 will hopefully mitigate that.

would you suggest destruction by method of overprint, then? sounds like it might be slower for the one-time cost, but faster from that point on?

given that i have my current concept of the terminal's content stashed away (needed for `notcurses_refresh()` and computing damage), i could even clear the screen, and reproduce what ought remain, especially in the case of a large graphic. either way, i'd prefer a one-time hit to any lingering phantom performance penalty.

**Comment by dnkl** [comment]
I think it'll be the safe bet, both in the result it produces, and in performance.

It's hard to say though. Erasing a large sixel line-by-line can be really slow too, since the sixel may have to be copied and truncated over and over again. You definitely want to use escape sequences that erase a swat of cells in one go, rather than, say, printing spaces.

There are escapes to do "rectangular editing" (and among them, a rectangular erase). Unfortunately they're not widely supported. Technically, they're only available on VT400 and newer (many terminals don't implement 400 features, or any 300 features for that matter).

But, "rectangular editing" has it's own feature number in the primary DA response: 28.

So, what I'm thinking is you can look for 28 in the DA response, ignore the VT level, and use DECERA (rectangular erase) if available. And fall back to ECH, ED, EL or whatever.

**Comment by dankamongmen** [comment]
yeah i've seen the rectangular cuts, but had poor results in terms of support. i ought give them a second try, though.

**Comment by dankamongmen** [comment]
closing this in favor of DECERA, if that ends up being workable. thanks for the detailed insights, @dknl!
