### ISSUE TITLE
notcurses-core.pc unconditionally depends on tinfo

### ISSUE THREAD

**Issue by kaniini** [dankamongmen/notcurses#1635]
On some systems, like Alpine, libtinfo is built into libncurses itself.  The .pc file needs to reflect that reality for those cases.

**Comment by dankamongmen** [comment]
i know i have something special-cased in there already for this...

```c
# some distros (<cough>motherfucking alpine</cough> subsume terminfo directly   
# into ncurses. accept either, and may god have mercy on our souls.             
pkg_search_module(TERMINFO REQUIRED tinfo>=6.1 ncursesw>=6.1)                   
set_property(GLOBAL APPEND PROPERTY PACKAGES_FOUND terminfo)                    
set_package_properties(terminfo PROPERTIES TYPE REQUIRED)    
```

so does alpine also not have ncursesw.pc any more?

oh you're talking about my output .pc; i'm a dumbass. thanks for the heads-up! 

so the problem is presumably emerging from

```
Requires.private: tinfo
```

i think this might (maybe not) also have something to do with #1098 (https://github.com/conan-io/conan-center-index/pull/4036).

**Comment by kaniini** [comment]
seems likely :)

**Comment by dankamongmen** [comment]
Alright, I'm now setting `Requires.private` based off whatever I find for `TERMINFO_LIBRARIES`, with the following output on my Arch laptop:

```
[grimes](0) $ cat notcurses-core.pc prefix=/usr/local
exec_prefix=/usr/local
libdir=${prefix}/lib
includedir=${prefix}/include

Name: notcurses
Description: TUI library for modern terminal emulators (core library)
Version: 2.2.10

Requires:
Requires.private: ncursesw
Libs: -L${libdir} -lnotcurses-core
Libs.private: -lunistring -lm
Cflags: -I${includedir}
[grimes](0) $ 
```

I think that'll work for you
