### ISSUE TITLE
mouse events

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#165]
Maybe. Desired for #162. Look into it, see how much of a pain in the ass it would be, how many setups we can handle with one chunk of ass-nasties, and make a decision. If this isn't in 1.0.0, I'll not be too upset at all, but it would be nice if it's not dumb.

**Comment by klamonte** [comment]
X10 mouse support (not ncurses) isn't too bad on encoding/decoding.  Ask the terminal for UTF-8, then SGR, and parse both unambiguously.  I've got code [here](https://gitlab.com/klamonte/jexer/blob/master/src/jexer/backend/ECMA48Terminal.java) (Java so blech, but hopefully pretty clear anyway, and MIT licensed) in parseMouse() and parseMouseSGR() as an example.

**Comment by dankamongmen** [comment]
Reading over the XTerm guide, I can indeed use X10 mode, but that only gets me button presses. I don't need general motion notification, but I *do* want motion notification while a button is held down (to support some big drag-and-drop dream I have for the ultramegaok demo). For that, I think the following class is perfect:

#define SET_BTN_EVENT_MOUSE 1002

```
Button-event tracking is essentially the same as normal tracking, but xterm also reports button-motion events. Motion events are reported only if the mouse pointer has moved to a different character cell. It is enabled by specifying parameter 1002 to DECSET. On button press or release, xterm sends the same codes used by normal tracking mode. On button-motion events, xterm adds 32 to the event code (the third character, C b ). The other bits of the event code specify button and modifier keys as in normal mode. For example, motion into cell x,y with button 1 down is reported as CSI M @ C x C y . ( @ = 32 + 0 (button 1) + 32 (motion indicator) ). Similarly, motion with button 3 down is reported as CSI M B C x C y . ( B = 32 + 2 (button 3) + 32 (motion indicator) ).

Any-event mode is the same as button-event mode, except that all motion events are reported, even if no mouse button is down. It is enabled by specifying 1003 to DECSET.
```

So button-event tracking seems to be exacrtly what i want. X10 also doesn't look like it handles scrollwheels. GOTTA HAVE MAH SCROLLWHEELS.

**Comment by dankamongmen** [comment]
btw @klamonte you claim to be using X10 (Mode 9), but your actual code appears to be using All (Mode 1003). am i missing something? I'm `looking at private String mouse(bool on)`. 1003 would seem to make more sense, especially in the presence of 1005/1006 as you have there.

Speaking of, why use 1005 in conjunction with 1006 and 1015? Is that a fallback configuration or something? I'll look into it.

But I think we want 1002 to (1) get all interesting events and (2) not be busied with uninteresting events.

**Comment by dankamongmen** [comment]
Upon calling `notcurses_mouse_enable()`, I'm now definitely seeing input for the following:

* clicking within the window
* losing focus on the window via mouse press in another window
* movement while mouse button held

but NOT for:

* movement without a button held
* button presses while we're not focused

which seems exactly what we want. Now I just need to break down those returns.

**Comment by klamonte** [comment]
> btw @klamonte you claim to be using X10 (Mode 9), but your actual code appears to be using All (Mode 1003). am i missing something?

Hmm, I've been referring to the entire protocol as "X10 mouse", with the barebones (single click only) as "X10 encoding".  A bit sloppy on my part looking at the doc further.

> I'm `looking at private String mouse(bool on)`. 1003 would seem to make more sense, especially in the presence of 1005/1006 as you have there.

I turn everything on: 1002 1003 1005 1006 in that order to provide graceful fallback.  Those terminals that do button tracking but not anyevent will see 1002, ignore 1003, and then give me enough for dragging/resizing windows but not tracking the mouse pointer.  Similarly, those that do UTF8 encoding but not SGR will see 1005, ignore 1006, and then give me something (I hope!) that doesn't break the UTF-8 stream when moving outside (160, 94).

FYI all of this finally got settled and landed in xterm itself only in 2012.  Prior to that it was the bees knees just to have basic clicks and wheel up/down working.

> Speaking of, why use 1005 in conjunction with 1006 and 1015? Is that a fallback configuration or something? I'll look into it.

I don't use 1015 because it can conflict with normal CSI M (delete line).  1006 has that '<' after the CSI that clearly separates it from normal CSI sequences, so is unambiguous.  I haven't run across a terminal sending CSI M to the application, but in theory one could, just like up/down/right/left sending CSI A/B/C/D.

> But I think we want 1002 to (1) get all interesting events and (2) not be busied with uninteresting events.

One other note: you may have to set TERM=xterm-1005 etc. to actually see these events.  At least I do when using ncurses, I don't know if that is ultimately exposed via terminfo or not.

**Comment by dankamongmen** [comment]
Now using button event tracking to decode up to 12 mouse buttons, press v release, coordinates, modifiers, and movement while pressed:

![2019-12-23-185143_722x1417_scrot](https://user-images.githubusercontent.com/143473/71385389-5561c300-25b5-11ea-9ba9-1d1f4228592c.png)
