### ISSUE TITLE
ncvgeom.rcell is never set

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#1665]
I don't see `ncvgeom.rcelly`+`ncvgeom.rcellx` being set, anywhere. Grep only finds the header file.

**Comment by dankamongmen** [comment]
yep. this will use a result calculated from `ncvisual_blitset_geom()`, so that the logic is in one place. it currently doesn't do this calculation:

```c
// FIXME we ought also do the output calculations here (how many rows x cols,                                                           
//   given the input plane vopts->n and scaling vopts->scaling)
```

i'll go ahead and implement this RSN (early this week, probably tomorrow).

**Comment by dankamongmen** [comment]
It would be nice to move forward on this. The difficulty, as I recall it, is getting the final character geometry out of `ncvisual_blitset_geom()`. Right now, the worst case would be sixel: we don't know the true number of rows occupied until `sixel_blit()` (which extends the logical number of pixels out to a multiple of 6, if the number of input pixels is not a multiple of 6). We'd need to get all of that information frontloaded to `ncvisual_blitset_geom()`, which requires some rather delicate work.

That's probably the thing to do, though, because we really ought be using that true logical value when doing early decisions like `ncvisual_scale()`.

ugh. for now i've marked `rcell{y,x}` as not yet being set. you can approximate them using `pix` / `scale`, of course....in which case, so can i. alright, i'm going to do that in `ncdirectf_geom()`. when we get the perfect values out of `ncvisual_blitter_geom()`, we'll kill this approximation (which will never be off by more than 1 in either direction).

**Comment by dankamongmen** [comment]
ok `rcelly` and `rcellx` are now being set. they'll be exact once the sixel overrun is taken into account, which i guess i could just do there, but i'd rather just get ncvisual_blitter_geom()` calculating it precisely, and handing that off.
