### ISSUE TITLE
2.2.10 LXTerminal notcurses_core_init returns NULL if with ncdirect_core_init and vice versa

### ISSUE THREAD

**Issue by schottstaedt** [dankamongmen/notcurses#1666]
I use both ncdirect and notcurses at the same time.  This has worked from the beginning until version 2.2.10 in Fedora 34 where I get NULL from notcurses_core_init if called after ncdirect_core_init, or vice versa.  I looked in NEWS.md, but don't see any warnings.  The code works in version 2.2.2 and all previous versions that I tried.  (I get the same behavior from notcurses_init+ncdirect_init).  When NULL is returned, I don't see any error message.

**Comment by dankamongmen** [comment]
on it. `ncneofetch` does the same thing, and i know it's still working. if you want to link / paste your code, i'll be able to figure it out pretty quickly. thanks a lot for your patience, and thank you for trying notcurses!

to take up the error level, try setting `loglevel` in the `notcurses_options` structure.

**Comment by schottstaedt** [comment]
The original code is hard to deal with (it's through an FFI from scheme), but this little program shows the problem.  It returns 2 pointers in 2.2.2 but whichever one is called second is nil in 2.2.10.  Now, I hope I get this copy/paste right):

#include <locale.h>
#include <notcurses/notcurses.h>
#include <notcurses/direct.h>

int main(int argc, char **arg)
{
  struct notcurses *nc;
  struct ncdirect *nd;
  nd = ncdirect_init(NULL, stdout, 0);
  fprintf(stderr, "%p\n", nd);
  nc = notcurses_init(NULL, NULL);
  notcurses_stop(nc);
  ncdirect_stop(nd);
  fprintf(stderr, "%p %p\n", nc, nd);
}

**Comment by dankamongmen** [comment]
ahhh, you mean *simultaneous* use of an `ncdirect` and a `notcurses`, i've got you. huh! i'd never considered this use case, since anything else generating output atop rendered mode is a recipe for trouble. but you were making effective use of it...

it no longer works because `ncdirect` now also registers signal handlers to ensure the terminal is restored on a fatal signal. the error is printed if you set the loglevel high:

```c
                                                        
  struct notcurses_options opts = {
    .loglevel = NCLOGLEVEL_TRACE,
  };
  nc = notcurses_init(&opts, NULL);                                                                  
```

```
[grimes](0) $ ./1666 
0x555e59814420
get_tty_fd:488:Returning TTY fd 4
is_linux_console:548:Not a Linux console, KDGETMODE failed
setup_signals:110:0x555e59814420 is already registered for signals (provided 0x555e5981d8f0) <-------
(nil) 0x555e59814420
[grimes](0) $ 
```

so, you can prevent this particular problem by supplying `NCOPTION_NO_QUIT_SIGHANDLERS` to `notcurses_init()`, or `NCDIRECT_OPTION_NO_QUIT_SIGHANDLERS` to `ncdirect_init()`. only one will go to register signal handlers if you do so. to match the old behavior you had, do the latter (`NCDIRECT_OPTION_NO_QUIT_SIGHANDLERS`).

i can't recommend this methodology, but that ought get you working agian.

if you'd like to talk to me about exactly what you're trying accomplish, there might be a better way to do it, or if not, i might be able to support you better.

**Comment by dankamongmen** [comment]
This change was introduced in 2.1.4. I didn't note the exact ramification you describe in `NEWS.md`, because it never occurred to me =]

```c
* 2.1.4 (2021-01-03):                                                           
  * Direct mode now supports `NCDIRECT_OPTION_NO_QUIT_SIGHANDLERS`, and by      
    default installs signal handlers similar to those of fullscreen mode.       
    They will attempt to reset the terminal, and propagate the signal.  
```

**Comment by dankamongmen** [comment]
ahhhh, but only late did i make two registering an actual error, after fixing a bug in the unit tests.

and i now realize that sretting this flag inhibits establishing signal handlers, but *NOT* establishing the lock. le sigh. i'll fix that, and the fix will be in `master` and 3.0.1. argh, sorry =[

**Comment by dankamongmen** [comment]
with the change i've just made, plus the change i suggested to your sample code, it now starts up (it *does* print a warning on shutdown, sorry):

```
[grimes](0) $ ./1666 
0x55ea7532e420
get_tty_fd:488:Returning TTY fd 4
is_linux_console:548:Not a Linux console, KDGETMODE failed
ncplane_new_internal:452:Created new 51x80 plane "std" @ 0x0

 notcurses 2.3.0 by nick black et al on xterm-256color
  51 rows 80 cols (63.75KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.0, 16B little-endian cells
  terminfo from ncurses 6.2.20200212
  avformat 58.76.100 avutil 56.70.100 swscale 5.9.100
Signals weren't registered for 0x55ea7532e420 (had (nil))
0x55ea753378f0 0x55ea7532e420
[grimes](0) $ 
```

```
[grimes](0) $ cat ../src/poc/1666.c 
#include <locale.h>
#include <notcurses/notcurses.h>
#include <notcurses/direct.h>

int main(int argc, char **arg) {
  struct notcurses *nc;
  struct ncdirect *nd;
  nd = ncdirect_init(NULL, stdout, NCDIRECT_OPTION_NO_QUIT_SIGHANDLERS);
  fprintf(stderr, "%p\n", nd);
  struct notcurses_options opts = {
    .loglevel = NCLOGLEVEL_TRACE,
  };
  nc = notcurses_init(&opts, NULL);
  notcurses_stop(nc);
  ncdirect_stop(nd);
  fprintf(stderr, "%p %p\n", nc, nd);
}
[grimes](0) $ 
```

**Comment by schottstaedt** [comment]
Thanks!  You ask what I trying to accomplish.  I'm writing a REPL for a version of Scheme (s7).  I first used notcurses about a year ago (version 1.5 or thereabouts), and used ncdirect nearly everywhere.  Since then I've moved nearly everything to notcurses, so the only ncdirect function I still use is ncdirect_cursor_move_yx.  I need to show where the next edit will take place, but ncplane_cursor_move_yx does not give the same functionality as the ncdirect function. The
ncplane cursor appears to be the shell's cursor (a red block in my case), rather than the blinking underline from ncdirect, and no matter what I do I can't get the ncplane cursor to display itself as I move it.  I'm probably missing something trivial.

**Comment by dankamongmen** [comment]
first off, awesome; one of my most beloved college professors, [olin shivers](https://www.ccs.neu.edu/home/shivers/), was a big scheme guy. he taught an awesome compilers class while i was at gy.

so reading your comment, what i gather you need is just a visible cursor in rendered mode. i'm guessing you've enabled the cursor with `notcurses_cursor_enable()`. there are a few strategies you could use.

* use an `ncreader` to drive your input, which has visible cursor support via `NCREADER_OPTION_CURSOR`
* if you're managing your own input, use `NCSTYLE_BLINK` together with your cursor glyph. many terminals don't support `NCSTYLE_BLINK`, though
* get a badass true pulsing cursor with `ncplane_pulse()`, using a 1x1 `ncplane` containing your cursor glyph

but you are correct -- rendered mode doesn't have any means to manipulate the "hardware cursor", save making it visible. which is stupid, because we absolutely manipulate it internally, all over the place. so i'm going to add

`notcurses_cursor_move_yx()`

and

`notcurses_cursor_yx()`

so you can do this trivially, just by setting it to enabled. know that it will be disabled for the duration of updating the screen, which shouldn't be a problem, but might make it flicker weirdly -- let me know if it looks like shit, and i'll see what can be done.

dude, you've been with me since 1.5? you're like my zhou enlai. you can ask for whatever feature you want. i had no idea i'd had serious users for so long; that's fucking awesome.

**Comment by dankamongmen** [comment]
if you're willing to put in the extra effort, though, that `ncplane_pulse()` solution would look really cool =D

**Comment by dankamongmen** [comment]
ok closing this up, assuming you find the initialization/signals changes above satisfactory.  i've added #1681 to add the hardware cursor features i described above. in the future, feel *encouraged* to reach out and ask for functionality that seems it ought be there, or even just for help (maybe use the Discussions area for this latter). i'm trying to get this library picked up by people, and the more info out there answering questions people are hitting etc, the better chance of that. thanks for the report!

**Comment by dankamongmen** [comment]
wait can't you just move it with `notcurses_cursor_enable()`?

**Comment by dankamongmen** [comment]
https://github.com/dankamongmen/notcurses/commit/50693fb8128aebf859eb0c014d942f15ed307e3e i updated `notcurses_init(3)` with some information on the hardware cursor

**Comment by schottstaedt** [comment]
> wait can't you just move it with notcurses_cursor_enable()?

Yes!  I knew it was something stupid on my part.  Thanks very much!

**Comment by dankamongmen** [comment]
awesome! i'm now pondering undoing the change i made to allow an `ncdirect` and a `notcurses` (or for that matter multiple of either) to coexist. it's just a really bad idea, and i can't think of any reason to do it -- if there is such a reason, i'd like to internalize the necessary functionality to rendered mode (e.g. `ncsubproc`). i assume you've eliminated this from your program, and it wouldn't be a problem for you anymore?

**Comment by schottstaedt** [comment]
> i assume you've eliminated this from your program, and it wouldn't be a 
> problem for you anymore?

Yes, that's correct.

**Comment by dankamongmen** [comment]
I've gone ahead and reverted this functionality, so it is no longer possible to have both a `ncdirect` and `notcurses` active in a single process, nor more than one of either. I've documented this in the man pages and `NEWS.md`. See #1706.
