### ISSUE TITLE
ncvisual_from_bgra() doesn't work properly

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1700]
Something must have changed in the last few weeks, since investigating issue #1699 I just realized blittling has stopped working properly in the rust wrappers. Maybe @dankamongmen you can think what's changed that could cause this bugs?

Using NCBLIT_PIXEL doesn't work anymore, rendering nothing (e.g.: [pixel-cell.rs](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/pixel-cell.rs), [issue-1559.rs](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-1559.rs)) 

And using NCBLIT_1x1, for example, to render a solid color rectangle shows only vertical. See new example [issue-1699.rs](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-1699.rs), which renders:

![image](https://user-images.githubusercontent.com/5832068/120109490-f325ce00-c169-11eb-8015-1a35623f46b4.png)

**Comment by joseluis** [comment]
from_bgra() renders badly but from_rgba() renders ok. The functions in rust are implemented exactly the same, so it must be a bug in the C code...

**Comment by joseluis** [comment]
I believe the bug must be in this part, in the from_bgra() function:
```c
    for(int y = 0 ; y < rows ; ++y){
      for(int x = 0 ; x < cols ; ++x){
        uint32_t src;
        memcpy(&src, (const char*)bgra + y * rowstride + x, 4);
        const uint32_t r = (src & 0xffllu) << 16u;
        const uint32_t b = (src & 0xff0000llu) >> 16u;
        data[ncv->rowstride * y / 4 + x] = (src & 0xff00ff00llu) | r | b;
      }
    }
```

vs the equivalent part in for from_rgba():
```c
    for(int y = 0 ; y < rows ; ++y){
      memcpy(data + (ncv->rowstride * y) / 4, rgba + rowstride * y, rowstride);
    }
```

**Comment by joseluis** [comment]
This says nothing about why NCBLIT_PIXEL stopped working though...

**Comment by joseluis** [comment]
I suspect the memcpy line should be:

```c
memcpy(&src, (const char*)bgra + y * rowstride + x * 4, 4);
```

Sadly I'll have to stop my investigation here....

**Comment by joseluis** [comment]
that seems to be the issue, so I went ahead and pushed the fix

**Comment by joseluis** [comment]
I'm gonna open a new issue for the invisible pixels

**Comment by dankamongmen** [comment]
Nice work on this, @joseluis ! You're the man!

**Comment by dankamongmen** [comment]
so i'm kinda catching up here and wanted to close out a few things

(1) you're not calling `_bgra()` by default, are you? it's possibly substantially slower than `_rgba()`, since we're all-RGBA internally
(2) things that changed recently include that we're once again honoring `leny`/`lenx` in `ncvisual_options`
(3) i've definitely tested sixels+kitty using both direct mode and rendered mode and all scaling types, though admittedly almost entirely with ffmpeg. things ought definitely be working, AFAIK. i've also bulked up the unit tests on this stuff, so i've got some more assurance on it. do you know of any current problems?
