### ISSUE TITLE
resizing bug when notcurses is compiled without multimedia support

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1705]
pixel-cell example run using notcurses compiled WITH multimedia support:
![image](https://user-images.githubusercontent.com/5832068/120388376-56129300-c32b-11eb-8d01-e50912f48f68.png)

and compiled WITHOUT multimedia:
![image](https://user-images.githubusercontent.com/5832068/120388687-befa0b00-c32b-11eb-8d48-cd82c6e57083.png)

that's on kitty, but the same corruption happens in xterm.

related #1699

**Comment by dankamongmen** [comment]
good work getting to the bottom of this! definitely my bug. i'll get on this for the imminent 2.3.2 release, huzzah.

**Comment by dankamongmen** [comment]
shit, this actually gets caught by a unit test; we're just not running with a sufficient `TERM` in our CI for this test to run.

```
[schwarzgerat](1) $ ./notcurses-tester -p ../data/ --abort-after=1
Running with LANG=en_US.UTF-8
Running with TERM=xterm-kitty (107x70)
[doctest] doctest version is "2.4.5"
[doctest] run with "--help" for options
===============================================================================
/home/dank/src/dankamongmen/notcurses/src/tests/bitmap.cpp:5:
TEST CASE:  Bitmaps
  SprixelMinimize

/home/dank/src/dankamongmen/notcurses/src/tests/bitmap.cpp:39: ERROR: CHECK( 0 == ncvisual_resize(ncv, 1, 1) ) is NOT correct!
  values: CHECK( 0 == -1 )

===============================================================================
/home/dank/src/dankamongmen/notcurses/src/tests/bitmap.cpp:5:
TEST CASE:  Bitmaps

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  SprixelMinimize

Aborting - too many failed asserts!
===============================================================================
[doctest] test cases:  1 | 0 passed | 1 failed | 47 skipped
[doctest] assertions: 10 | 9 passed | 1 failed |
[doctest] Status: FAILURE!
[schwarzgerat](1) $ 
```

**Comment by dankamongmen** [comment]
you know, i don't think we *have* an implementation for resize without a multimedia library. i mean, that's why it's returning -1.

**Comment by dankamongmen** [comment]
yeah i didn't write any such thing, heh. there's no `visual_implementation` in this case. well, there is, but it's this (from `none.c`):

```c
// resize, converting to RGBA (if necessary) along the way                                                 
int none_resize(ncvisual* nc, int rows, int cols){                                                         
  // we'd need to verify that it's RGBA as well, except that if we've got no                               
  // multimedia engine, we've only got memory-assembled ncvisuals, which are                               
  // RGBA-native. so we ought be good, but this is undeniably sloppy...                                    
  if(nc->pixy == rows && nc->pixx == cols){                                                                
    return 0;                                                                                              
  }                                                                                                        
  return -1;                                                                                               
}
```

**Comment by db48x** [comment]
You could plug in a generic crate like https://docs.rs/image/0.18.0/image/imageops/fn.resize.html

**Comment by db48x** [comment]
Except I forgot that this is a C library!

**Comment by dankamongmen** [comment]
alright, here's how we're gonna get this done:

* #1576 wants `NCSCALE_INFLATE`, which requires inflate support to arbitrary sizes
* i'll implement that as outlined, sans interpolation, suitable for pixel graphics but not great for other images
* for now, `ncvisual_resize()` will be a frontend to this inflator
* we might add a smarter scaler for this later, but maybe not

the theory here is that if you don't have multimedia capabilities, you're not opening files with complex images, but instead just building up pixel art by hand, and thus wouldn't need interpolative scaling. that doesn't really hold for all cases, though.

**Comment by dankamongmen** [comment]
I've just about got the generic noninterpolative inflate/deflate code working (there's a unit test failing). I've hooked it up to both the `none` multimedia engine, and the no-engine case (i.e. just `libnotcurses-core`). it's resizing correctly, but not yet writing entirely correct data. it *has* resolved the `Bitmaps::BitmapStretch` unit test which was failing before.

**Comment by joseluis** [comment]
I'm reopening since I still see the same behaviour, without multimedia and using kitty the pixel-cell example is corrupted as shown. The difference is now xterm doesn't render pixels anymore with or without multimedia support.

with kitty:
![image](https://user-images.githubusercontent.com/5832068/120683173-96921e00-c49d-11eb-9524-57665f90da4e.png)

with xterm:
![image](https://user-images.githubusercontent.com/5832068/120683226-a7429400-c49d-11eb-925a-68021fafaf8f.png)

**Comment by db48x** [comment]
I see the same, but it also prints out an error: “Error: NcError { int: -1, msg: "NcVisual.render()" }”

**Comment by dankamongmen** [comment]
Lots of work today for #1718, as seen in #1725. But that was all to bring implicit scaling to `ncvisual_blit()` in the no-engine case. Let me take a fresh look at this. Seven hells.

**Comment by dankamongmen** [comment]
hey @joseluis , `wipebitmap` is something of an inspection-based test of bitmap stuff. can you run `wipebitmap 2>/dev/null` and make sure the output looks sane? you're not getting any output on xterm? :( things are working fine for me over here on a first look...

**Comment by dankamongmen** [comment]
here's what i get in xterm:

![2021-06-06-024704_884x1292_scrot](https://user-images.githubusercontent.com/143473/120915411-829f1580-c671-11eb-9714-479ce75aad05.png)

**Comment by dankamongmen** [comment]
and in kitty, i get the same thing:

![2021-06-06-024752_1072x1417_scrot](https://user-images.githubusercontent.com/143473/120915436-9cd8f380-c671-11eb-9859-cddd4a3dba0a.png)

**Comment by dankamongmen** [comment]
and this is definitely a multimedia-free build:

```c
[schwarzgerat](0) $ ./caps-rendered 

 notcurses 2.3.2 by nick black et al on xterm-kitty
  70 rows (20px) 107 cols (10px) (117.03KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.1 20210110, 16B little-endian cells
  terminfo from ncurses 6.2.20201114

 Warning! Notcurses was built without multimedia support.
 Colors: 256 rgb: y ccc: y setaf: y setab: y
 sgr: y sgr0: y op: y fgop: y bgop: y
 rows: 70 cols: 107 rpx: 20 cpx: 10 (1400x1070)
 RGBA pixel graphics supported
 UTF8: y quad: y sex: y braille: y images: n videos: n
 Quads:  ▘▝▀▖▌▞▛▗▚▐▜▄▙▟█
 Sextants:  🬀🬁🬂🬃🬄🬅🬆🬇🬈🬊🬋🬌🬍🬎🬏🬐🬑🬒🬓▌🬔🬕🬖🬗🬘🬙🬚🬛🬜🬝🬞🬟🬠🬡🬢🬣🬤🬥🬦🬧🬨🬩🬪🬫🬬🬭🬮🬯🬰🬱🬲🬳🬴🬵🬶🬷🬸🬹🬺🬻█
 Braille: ⠀⢀⢠⢰⢸⡀⣀⣠⣰⣸⡄⣄⣤⣴⣼⡆⣆⣦⣶⣾⡇⣇⣧⣷⣿
 Bottom eighths:  ▁▂▃▄▅▆▇█
 background of 0x000000 is considered transparent
 cup: y vpa: y hpa: y
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
this output is very similar, if not equal to, what i get using an `ffmpeg`-backed build -- where, once again, i get the same output in xterm and kitty. perhaps something got fixed in tonight's work on #1718? otherwise, we'll have to drill down into what's different between our setups.

is the seemingly random blob of color what you're expecting to see, or is it being corrupted the same way across all configurations? is it supposed to be that original image you display? if so, i'm suspecting some kind of problem in how you're calling me, since everything's resulting in the same image (for me).

let me know if the #1725 changes led to different results for you, thanks.

**Comment by joseluis** [comment]
@dankamongmen I updated to the latest source, compiled it without multimedia support, and it does seem to work well in xterm. I also run wipebitmap and it does look right.

The only thing is the scaled image is too short. See the following augmented screenshot. You can see there are 4 rows not as tall as they should.
![image](https://user-images.githubusercontent.com/5832068/120928349-99328480-c6e4-11eb-9995-b5cb3b4a3e11.png)

**Comment by dankamongmen** [comment]
progress!

**Comment by dankamongmen** [comment]
if it is easy for you to do, could you see if the truncated scaled image breaks the same way with an `ffmpeg` backend? if it's a PITA, i can get to it later. if this is now backend-independent, i'd like to make a new bug on it.

**Comment by dankamongmen** [comment]
wait, are you sure that this is a bug? let me go look at your code.

**Comment by dankamongmen** [comment]
![2021-06-06-124207_884x556_scrot](https://user-images.githubusercontent.com/143473/120932645-9d4eaa00-c6c4-11eb-9343-752d49fef772.png)

looks like the same thing happens with `ffmpeg` as a backend (here you can see the definite difference between scaling and inflating).

**Comment by joseluis** [comment]
> if it is easy for you to do, could you see if the truncated scaled image breaks the same way with an `ffmpeg` backend? if it's a PITA, i can get to it later. if this is now backend-independent, i'd like to make a new bug on it.

Yes, it happens the same

![image](https://user-images.githubusercontent.com/5832068/120932792-84132100-c6f7-11eb-8c58-7a3c64610ca1.png)

side by side:
![image](https://user-images.githubusercontent.com/5832068/120932925-10bddf00-c6f8-11eb-832e-d2cf9b795c2d.png)

**Comment by joseluis** [comment]
in my case, at 13x6, it's 4 pixels short, in your case, at 23x11 it's 2 pixels short:
![image](https://user-images.githubusercontent.com/5832068/120933014-87f37300-c6f8-11eb-8fa3-ca3b2f557825.png)

**Comment by dankamongmen** [comment]
so first off @joseluis , not sure if you know, but you can leave out the `leny`/`lenx` arguments in `ncvisual_options`, and it'll go through the width of the image (accounting for any `begy`/`begx`). you don't have to always provide the pixel geometry.

if i understand corrrectly, you have a 13x6 image (or whatever your cell-pixel geometry is). then you inflate it by 4x, to 52x24. that will be 5 cell rows, because 52 % 6 != 0 (sixels must be expressed in multiples of 6 rows). we instead have to go up to 54 pixels of sixel target. it will be 4 columns. you're creating without a plane, so you ought get one back that's 5 tall and 4 wide. your picture on the right really ought be showing the 4 pixel rows of the 5th cell row that we're *not* drawing to.

then you're creating a 4x4 plane and using `NCPLANE_SCALE`. ok, so it wants to make it as big as it can, while preserving aspect ratio. but it has to fit in 4x4. ok, so let's scale it to 52x24. great. but your inflate has more room to work with. it gets to define its own plane. so since you wanted a 4x increase, but 4x|height| % 6 != 0, it's gonna need two extra rows of pixels. it seems the problem is that we populated them rather than leaving them transparent. i think the figure on the left has the correct height.

**Comment by dankamongmen** [comment]
ok, closing this down and making a new bug for the scale/inflate mismatch. thanks for the good testing! #1728 has been created.

**Comment by joseluis** [comment]
The shorter cells are 3x scaled instead of 4x.

In your case, it happens every 11 rows +1 (the num of pixel columns of your cell):
![image](https://user-images.githubusercontent.com/5832068/120933223-69da4280-c6f9-11eb-8a85-ed8a41b62c54.png)

In my case, it happens every 3 rows +1 (half the num of pixel columns of my cell):
![image](https://user-images.githubusercontent.com/5832068/120933468-99d61580-c6fa-11eb-8072-083d3918a02f.png)

**Comment by dankamongmen** [comment]
yep, i see what's going on i think. will hopefully get to it in a few hours, but am about to take a walk. throw any further comments into #1728 please, as this issue is cashed out.

**Comment by dankamongmen** [comment]
i just sent you a PR, @joseluis . if you change your `ncplane_options` to request 5 rows, things work. this will be safe in this particular context, because the width is always going to be your limited for `NCSCALE_SCALE`. if you didn't feel safe about that, i'd recomment first doing the operation which creates its own ncplane, and then using `ncplane_dim_y()` on that result to size your precreated plane. when #1684 is done, you'll be able to get the necessary size using `_geom()`, but right now it doesn't take sixel extension (this exact problem) into account.
