### ISSUE TITLE
ncdirect_box() doesn't handle default fg/bg correctly

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#1752]
Something like this:

```c
uint64_t box_color
ncchannels_set_fg_rgb8(&box_color, 255, 255, 255);
ncchannels_set_bg_default(&box_color);
ncdirect_rounded_box(n, box_color, box_color, box_color, box_color, img_y[i] + 4, img_x[i] + 4, 0);
```

Results in this (magenta is the default background color). The upper and lower horizontal lines are rendered on black background:
![ncdirect-box](https://user-images.githubusercontent.com/14031526/121522488-73172800-c9f5-11eb-8d0a-ed3a3a7b3f1f.png)

**Comment by dankamongmen** [comment]
should be an easy fix, thanks for the report! i'll hopefully get to this tonight.

**Comment by dankamongmen** [comment]
> ```c
> uint64_t box_color
> ncchannels_set_fg_rgb8(&box_color, 255, 255, 255);
> ```

BTW, you want a hard `box_color = 0` here; what you're doing is unsafe. `ncchannels_set_fg_rgb8()` only touches the color bits of the foreground word, leaving the others unmodified. since you're not initializing them, there's garbage.

either `box_color = 0` or `box_color = CHANNELS_RGB_INITIALIZER(255, 255, 255, 0, 0, 0)`, followed by your `ncchannels_set_bg_default()`, would be fine.

i'm not sure how i can make this more explicit in docs, hrmmm.

were you not getting this warning?

```c
In file included from /home/dank/src/dankamongmen/notcurses/src/tests/main.h:9,
                 from /home/dank/src/dankamongmen/notcurses/src/tests/direct.cpp:1:
/home/dank/src/dankamongmen/notcurses/include/notcurses/notcurses.h: In function ‘void _DOCTEST_ANON_FUNC_2()’:
/home/dank/src/dankamongmen/notcurses/include/notcurses/notcurses.h:296:29: warning: ‘chans’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  296 |   return ncchannels_bchannel(channels >> 32u);
      |          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/dank/src/dankamongmen/notcurses/src/tests/direct.cpp:57:14: note: ‘chans’ was declared here
   57 |     uint64_t chans;
      |              ^~~~~
```

**Comment by dankamongmen** [comment]
hrmmm...it's working for me, or at least seems to be:

```c
  SUBCASE("BoxDefault") {
    uint64_t chans = CHANNELS_RGB_INITIALIZER(255, 0, 255, 0, 0, 0);
    ncchannels_set_bg_default(&chans);
    ncdirect_set_bg_rgb8(nc_, 0x88, 0x88, 0x88);
    printf("test background\n");
    CHECK(0 == ncdirect_rounded_box(nc_, chans, chans, chans, chans,
                                    8, 8, 0));
printf("\n");
sleep(5);
  }
```
![2021-06-10-164048_1072x664_scrot](https://user-images.githubusercontent.com/143473/121594092-9e584200-ca0a-11eb-8676-a9f9da406237.png)

**Comment by dankamongmen** [comment]
oh wait i see what you mean. i think there is confusion about the meaning of "default background color"

**Comment by dankamongmen** [comment]
in the Notcurses context (and `terminfo(5)` etc.), the concept of "default background color" is distinct and separate from that of "current background color".

default background color: the color used for the background following an `op` control sequence, usually configured by the user. it might be transparent. it is used when the current background color is reset.

current background color: the color used for output until the color is changed.

so your background is magenta presumably through a `ncplane_set_base()`, right? or possibly you wrote spaces into all those cells, who knows. so your current background color is magenta. when you call `ncdirect_box()`, you're replacing both fg and bg colors. you're in this case setting the *current* background color to the *default* background color.

if you want the box to have a magenta background, you need set that in `box_color` as the background.

i don't have any mechanism for indicating "retain the existing background" via an ncchannel. in rendered mode, we have the somewhat curiously-named `_stained()` functions, which replace glyph content while retaining stylings. i can't even really do that in direct mode, because i don't know the style of arbitrary target cells. you can use `ncdirect_bg_rgb()` to get the current background color, though, and use that to seed your `box_color`.

please reopen if any of this analysis is flawed, or if you have suggestions for improvement! thanks!

**Comment by dnkl** [comment]
> BTW, you want a hard box_color = 0 here; what you're doing is unsafe. ncchannels_set_fg_rgb8() only touches the color bits of the foreground word, leaving the others unmodified. since you're not initializing them, there's garbage.

> either box_color = 0 or box_color = CHANNELS_RGB_INITIALIZER(255, 255, 255, 0, 0, 0), followed by your ncchannels_set_bg_default(), would be fine.

This is what I had from the beginning, but then started changing things up when I noticed the background color issue.

> so your background is magenta presumably through a ncplane_set_base(), right? or possibly you wrote spaces into all those cells, who knows

No, I configured the default bg in my terminal to be magenta, to highlight the issue (since it was hard to see with my normal terminal bg color, which is pretty close to black, but not quite). Sorry, should have been more clear about this.

In other words, my _entire terminal window_ was magenta **before** I ran my notcurses application.

So, what I'm really looking for, is a way to draw a box, with colors equivalent to `\e[37m\e[49m`. I.e. white on top of my terminal's default background. I thought that was what `ncchannels_set_bg_default(&box_color();` did?

The reason I think this is a bug, is because the vertical left/right lines are rendered correctly (or perhaps I should say - as I expect them), while the upper/lower ones are not.

We can even see this in your screenshot: the side lines have transparent background, while the corners and the lower and upper lines have a black background. Put differently, even if I have misunderstood the "default" color concept, shouldn't all the lines be rendered with the same background color, regardless of what that color is (assuming you use the same color for ul/ur/ll/lr)?

**Comment by dankamongmen** [comment]
thanks for the detailed criticism and notes. i've reopened this and will take a deeper look into it today. thanks as always for driving high quality!

ok so your default color *as configured* is magenta? yeah, i didn't grok that, and it changes everything. i thought it a bit strange that you would be confused about default colors =]. i'll get on this ASAP.

**Comment by dankamongmen** [comment]
confirmed the breakage locally with `boxdefault` PoC

**Comment by dankamongmen** [comment]
problem identified, fix incoming

**Comment by dankamongmen** [comment]
ok yeah pretty obvious problem. in rendered mode's `ncplane_box()`, we're passing `nccell`s with their own inbuilt color information, and then just calling `ncplane_putc()`, which sets everything up properly. in `ncdirect_box()` we don't have such luxuries, and must set that up ourselves, but we're only handling the RGB case. need to handle both the default and palette-indexed cases at all points.

**Comment by dankamongmen** [comment]
![2021-06-12-102058_884x556_scrot](https://user-images.githubusercontent.com/143473/121779079-eb9df600-cb67-11eb-8674-eb8dced168eb.png)

looking much better!

**Comment by dankamongmen** [comment]
alright, this looks mostly fixed, but i'm going to audit a few things before calling this closed.

**Comment by dankamongmen** [comment]
at least one problem still exists: if we run `ncdirect_box()` at the bottom of the terminal, we get a big blast of crap following the top border. this smells of a `\n` vs `\v` issue.

![2021-06-12-102546_884x556_scrot](https://user-images.githubusercontent.com/143473/121779208-8f87a180-cb68-11eb-9682-47ce142030f0.png)

**Comment by dankamongmen** [comment]
hrmm that has something to do with the `test background` output; this doesn't happen when `ncdirect_box()` is run by itself.

**Comment by dnkl** [comment]
> hrmm that has something to do with the test background output; this doesn't happen when ncdirect_box() is run by itself.

Fairly sure that when you print `test background`, you leave the _current_ color gray. When the terminal scrolls, it fills the newly scrolled in lines with the _current_ background color, not the _default_ one. Assuming the terminal has the `bce` capability.

**Comment by dankamongmen** [comment]
> > hrmm that has something to do with the test background output; this doesn't happen when ncdirect_box() is run by itself.
> 
> Fairly sure that when you print `test background`, you leave the _current_ color gray. When the terminal scrolls, it fills the newly scrolled in lines with the _current_ background color, not the _default_ one. Assuming the terminal has the `bce` capability.

yep, that's exactly it

**Comment by dankamongmen** [comment]
that's gonna be another bug. that requires some thought -- what does the user want? either way, i'll want to abstract over bce vs no bce. calling this closed.

**Comment by dnkl** [comment]
Just tested this; works like a charm now, thanks!

**Comment by dankamongmen** [comment]
great! you may safely target this for notcurses 2.3.4+. don't hesitate to file similar bugs -- i wouldn't be surprised if there are more of them lurking in ncdirect (which, as noted, didn't initially get the love that rendered mode did). also, i've created a bug about bce (#1757).
