### ISSUE TITLE
wezterm updates badly a text plane over an updated visual 

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1832]
This happens in wezterm, but not in xterm nor alacritty.

A plane over another plane rendering a visual is shown ok, until the underlying plane gets updated. Then it shows all black.

Notice the small yellow plane with the slide counter, on the top left:
![image](https://user-images.githubusercontent.com/5832068/123524776-c44d3a00-d6cc-11eb-988d-f07df79a4508.png)

But after the underlying plane gets updated from a new visual, the plane shows all black and the onbly visible cells are the ones that are different. The counter in this case.
![image](https://user-images.githubusercontent.com/5832068/123524813-fd85aa00-d6cc-11eb-8adc-63518f2bb44a.png)

Screenshots taken from the new [plotters-examples](https://github.com/dankamongmen/notcurses-rs/blob/master/examples/plotters-examples.rs) example.

**Comment by dankamongmen** [comment]
i'll look into this shortly. WezTerm doesn't get as much testing as others do, because i can only build it on my laptop (my workstation is Debian, and its cargo can't build WezTerm, and i'm uncomfortable with the idea of running nightly rust outside my package manager). my laptop is arch, and anything goes there.

**Comment by joseluis** [comment]
> WezTerm doesn't get as much testing as others do, because i can only build it on my laptop 

FWIW I just [download the nightly AppImage from here](https://wezfurlong.org/wezterm/install/linux.html).

**Comment by dankamongmen** [comment]
huh i just grabbed the nightly appimage and `notcurses-info` worked alright for me. let me play around with geometry some and see if i can reproduce.

**Comment by dankamongmen** [comment]
htmmm

![2021-06-27-095146_1254x1417_scrot](https://user-images.githubusercontent.com/143473/123547065-4e2cef80-d72d-11eb-9247-f81383d9b429.png)

see anything obviously different?

**Comment by dankamongmen** [comment]
do you have one of those handy examples to reproduce this behavior?

**Comment by joseluis** [comment]
I dunno... I just downloaded the latest nightly, and with the latest notcurses master this is the result for me:

![image](https://user-images.githubusercontent.com/5832068/123547413-fad49480-d760-11eb-9ada-6a23949acbca.png)

**Comment by dankamongmen** [comment]
hrmm, looks like WezTerm is another one that claims `blink`, but doesn't actually support it.

> do you have one of those handy examples to reproduce this behavior?

oh i meant the stuff at the top

**Comment by joseluis** [comment]
I can make a reduced example, but in the meantime https://github.com/dankamongmen/notcurses-rs/blob/master/examples/plotters-examples.rs

**Comment by joseluis** [comment]
I've just pushed the minimal example [issue-1832](https://github.com/dankamongmen/notcurses/blob/f8747ea3e97bad59005c949de05eb359d9570b10/rust/examples/issue-1832.rs)

![image](https://user-images.githubusercontent.com/5832068/123548550-76d0db80-d765-11eb-8497-784efba9e8d8.png)

**Comment by dankamongmen** [comment]
thanks! i'll take a look at it...probably tomorrow, because i'm about to go drink eight pitchers of mimosas

**Comment by dankamongmen** [comment]
did exactly that, no shape to code now

![PXL_20210627_163115895](https://user-images.githubusercontent.com/143473/123558068-65d29b00-d762-11eb-8279-0b527bb2eeef.jpg)

**Comment by joseluis** [comment]
DW enjoy man!

**Comment by dankamongmen** [comment]
i was pretty certain i'd filed a bug for @wez regarding wezterm's sixel transparency, and he'd refused, but searching now, i can't find it. maybe i never did? come to think of it, i think i'm confusing wezterm for alacritty. alright, imma go file this on wezterm, and maybe it gets fixed there. either way, i'll determine whether this is the cause of all these issues or not.

**Comment by dankamongmen** [comment]
yeah, that's exactly what's going on. i'm shocked i didn't immediately recognize it from your writeup. here's what's going on, and why it leads to that result:

1) you write the first image, good good
2) you write the text above it. this blows away the cells on which you write the text. life is good.
3) you load the new image
  3a) as i encode the new image to sixel, i am consulting the TAM (transparency-annihilation matrix)
  3b) i see that these cells have text above them (i.e. they're in the ANNIHILATED state)
  3c) i thus do not encode pixels at these locations, and continue to leave the cells ANNIHILATED, **relying on transparency for unspecified pixels in a sixel**
  3d) wezterm consumes our glyphs as if they were tasty children, and it a confused and irritable velociraptor 
  3e) having written transparent cells where we need the text, i needn't update the text, and don't
  3f) you only have a '5', because *it was the only glyph that changed* (thus it got redrawn)

i could work around this by reprinting all glyphs in this case, but (a) that leads to flicker and (b) we really need transparency for other situations. i'll file a bug.

**Comment by dankamongmen** [comment]
https://github.com/wez/wezterm/issues/942

**Comment by dankamongmen** [comment]
if wezterm makes this change, everything will automatically be fixed. otherwise, i can put code in to drop the TAM between frames, which will resolve your particular problem (but not other problems). i'll furthermore have to key this off of detecting wezterm, unless a terminfo capability is added to differentiate this behavior from transparency.

**Comment by joseluis** [comment]
It seems the issue doesn't happen if the background plane is marked as scrolling

**Comment by dankamongmen** [comment]
i suspect that @wez's recent work resolves this. try the nightly wezterm build and you'll see this fixed, i bet. i can confirm `notcurses-demo` is now working in wezterm, frabjous day!
