### ISSUE TITLE
support kitty/iTerm/VTE-style ASUs

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1845]
the thread at https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/2 seems to suggest that @kovidgoyal implemented synchronized updates, but probably before consensus settled `$2026`. i don't see anything on the kitty extensions page about them. determine whether kitty supports ASUs, and detect+support them if so.

**Comment by kovidgoyal** [comment]
It does via the original and extensible DCS= escape code. kitty, iTerm and VTE were the first terminal emulators to add support for it and they all used DCS as was agreed originally, before terminal-wg aka Bikeshedder's Anonymous got started. As for detecting support for it dont bother, it's been in kitty for years. Since you already detect terminal name, if its kitty assume it is supported.

**Comment by dankamongmen** [comment]
will do, and thanks. do you have any intention of moving to the $2026 mechanism? i have no particular preference since i'll need carry around backwards-compat code for a good bit if you do, though it would eliminate the distinct path down the road.

**Comment by dankamongmen** [comment]
it looks like this might also be the method alacritty uses https://github.com/alacritty/alacritty/commit/9575aed68197ba783e50b922a6c3f9a78b8c7048

**Comment by dankamongmen** [comment]
oh, it looks like `DCS = [12] s` is the only method used, so it's just a matter of detection being available, great.

**Comment by kovidgoyal** [comment]
Yeah 2026 is bloody silly. The entire justification for it comes down to Apple's Terminal doesn't parse DCS and because I cant think of any extensions to this feature right now, means there cant possibly be any, so use a binary flag for it instead of an extensible escape code, which just means some poor future person that wants to add say, a configurable timeout/max size for waiting they will need a whole new escape code.

As far as I know every terminal that supports it supports the DCS version or both versions. The choice of which to use should be obvious. The *only* downside to using DCS is it will break on Apple's Terminal. Am sure Apple has the resources to implement proper DCS parsing in their terminal, if the need arises.

As for detection, there shouldn't be any need for it at all. This escape code has no unwelcome side effects (barring apples terminal) so just emit it unconditionally, or possibly blacklist apples terminal if you can detect that.

**Comment by kovidgoyal** [comment]
Actually, I think contour supports only 2026, though I may be misremembering.

**Comment by dankamongmen** [comment]
well in both cases it's just the DCS method to emit; 2026 is just to discover, right? either way, it's now supported for kitty+vte+iterm+alacritty without discovery, based off XTversion (or `TERM` in the case of XTVERSION-less alacritty). i also fixed a bug in my ASU routines brought to light by kitty, so this was time very well spent.

`intro` now runs in kitty without any flicker =].

**Comment by dankamongmen** [comment]
oooh we could save a system call here (and have the initial data arrive with the begin DCS) if we just allocated an extra few (constant) bytes, began writing that many bytes into the buffer, and filled in the Begin-SU prior to the write (when we have the frame length, and make the decision to SU or not).

**Comment by kovidgoyal** [comment]
On Mon, Jun 28, 2021 at 08:52:54PM -0700, Nick Black wrote:
> well in both cases it's just the DCS method to emit; 2026 is just to discover, right? either way, it's now supported for kitty+vte+iterm+alacritty without discovery, based off XTversion (or `TERM` in the case of XTVERSION-less alacritty). i also fixed a bug in my ASU routines brought to light by kitty, so this was time very well spent.

No, it's 2026 to turn on off with SM/RM and 2026 with DECQRM to detect.

> 
> `intro` now runs in kitty without any flicker =].

Cool :)

**Comment by dankamongmen** [comment]
hey @dnkl  you might want to check out `xray` since i made this change -- things seem significantly chunkier there now. i inspected the foot code and it looks like you're advertising with 2026 and implementing DCS, which is what i targeted. i need to go check who wants SM/RM2026 to engage, because i'm not sending that to anyone, sigh.

**Comment by dnkl** [comment]
> you're advertising with 2026 and implementing DCS

Foot supports **both** 2026 **and** DCS for ASU. But like the good man @kovidgoyal said; they aren't related. The whole idea with the DCS sequence is that you can (should be, if it weren't for a couple of buggy terminals) use it without quering for it - terminals _should_ ignore DCS sequences they don't support. If you've detected 2026 support in a terminal, you should use 2026 SM/RM, **not** the DCS sequence. Contour for example, **only** implements 2026, not the DCS.

> things seem significantly chunkier there now

I haven't checked today, but yesterday when I tested `notcurses-info`, it emitted ESU **before** BSU, leading to a 1 second freeze, before the output appeared. 1 second is foot's ASU timeout. For some this didn't always happen. But in ~9/10 times, `notcurses-info` exited without a final ESU. That would explain a "chunkier" xray (or chunkier anything, really).

**Comment by dnkl** [comment]
> I haven't checked today, but yesterday when I tested notcurses-info, it emitted ESU before BSU

Thinking back, it might also have been **two** ASUs, where the final one was never terminated. In any case, `notcurses-info` exited without a final ESU.

**Comment by dankamongmen** [comment]
> I haven't checked today, but yesterday when I tested `notcurses-info`, it emitted ESU **before** BSU, leading to a 1 second freeze, before the output appeared. 1 second is foot's ASU timeout. For some this didn't always happen. But in ~9/10 times, `notcurses-info` exited without a final ESU. That would explain a "chunkier" xray (or chunkier anything, really).

this is fixed as of about an hour ago =]

**Comment by dankamongmen** [comment]
> > I haven't checked today, but yesterday when I tested notcurses-info, it emitted ESU before BSU
> 
> Thinking back, it might also have been **two** ASUs, where the final one was never terminated. In any case, `notcurses-info` exited without a final ESU.

yeah what was going on was i was dropping the BASU onto stdio without a flush, and then writing the bulk out with `write()`, so the BASU would *most of the time* follow the EASU, at what could look like random times. i'm now filling the BASU directly into the bulk buffer, which fixes this and saves a system call.
