### ISSUE TITLE
use CSI 14 t where TIOCGWINSZ ioctl isn't available

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1891]
on at least windows, i assume we don't have `TIOCGWINSZ` as an `ioctl` (maybe we do? who knows). when we move to support it, try using `CSI 14 t` to recover the window geometry in pixels. to use this as a substitute, we would need put it (and the resultant round trip) into `notcurses_resize()`, which is kinda lame, so look for a native call that includes this functionality.

**Comment by dankamongmen** [comment]
though it might be that neither of these will work with Windows Terminal: https://github.com/microsoft/terminal/issues/8581

**Comment by WSLUser** [comment]
So in this case, I'd NOT use Windows Terminal as the base. Instead I'd look at the other terminals that run on Windows. Unfortunately though, since ConPTY doesn't have a pass-through mode, you're likely going to find very few terminal emulators capable of supporting this. MinTTY for example would be a terminal that completely supports these along with Sixel and may be your only viable option for testing. If you do choose to use that terminal, you don't need to install Cygwin or Msys2 to run it, the necessary dlls are included in WSLtty or Git bash.

**Comment by dankamongmen** [comment]
we're now sending CSI 14t in our initial query, and parsing the response. confirmed that it works.
