### ISSUE TITLE
get drone or github actions working with cobra-la

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1928]
cobra-la, @michaelsbradleyjr 's stalwart MacMini, ought be pressed into service for CI. if docker runs on mac (it appears it does), it ought be pretty trivial for me to get it enslaved to our drone at https://drone.dsscaw.com:4443/. we should maybe also hook it up to our GitHub Actions.

**Comment by michaelsbradleyjr** [comment]
Docker runs on mac, but afaik there's no such thing as macos images for docker, i.e. [Docker Desktop for Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac) can only be used to run linux containers, though maybe that's what you have in mind and I misunderstood.

It should be possible to have GitHub Actions run jobs on it, though I've never tried something like that, could be fun. I'm not sure if such a setup is possible with the free tier of GHA.

**Comment by dankamongmen** [comment]
nope, you interpreted me correctly, how absolutely infuriating

**Comment by WSLUser** [comment]
Not that I want to have you change your whole build pipeline but Azure Pipelines does include a Mac option, not just Windows or Linux. One would think that since Azure Pipelines supports building on Mac, Github would update to do similar. You may just have to set up an exclusive build CI/CD just for Mac using Azure Pipelines. As an OSS project, you should be able to do this for free but probably have to talk with somebody in MS to get it free.

**Comment by michaelsbradleyjr** [comment]
> One would think that since Azure Pipelines supports building on Mac, Github would update to do similar.

I'm not sure I understand. GitHub Actions does support building on macos and there is already a GHA workflow in this repo that builds on macos, though it has to be triggered manually per changes in #1764.

**Comment by michaelsbradleyjr** [comment]
See #1937.

**Comment by dankamongmen** [comment]
w00t, fanrtastic work @michaelsbradleyjr , far better than what i'd originally hoped for
