### ISSUE TITLE
iTerm2 XTVERSION lexing seems busted

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#1944]
It's probably *"due to OSX lacking support for most of Unicode 13"* as [mentioned](https://github.com/dankamongmen/notcurses/issues/1936#issuecomment-881031678) in #1936.

Here are some screenshots (I've made sure LANG, etc. are set correctly):

**iTerm2**
![image](https://user-images.githubusercontent.com/194260/125988559-c36ca419-03d1-4f4f-9727-c9d88d34c82e.png)
**Kitty**
![image](https://user-images.githubusercontent.com/194260/125988593-a1b9b285-e994-43a6-83bc-65939bb718ab.png)
**Alacritty** 
![image](https://user-images.githubusercontent.com/194260/125988624-377b158a-7c9a-497a-998e-c33e24174f66.png)
**Terminal.app** (ships with macOS)
![image](https://user-images.githubusercontent.com/194260/125988501-870c4e79-3781-482f-ab7b-10c6fd7e691e.png)

**Comment by dankamongmen** [comment]
so most of these look correct to me (Terminal.app definitely has real problems).

* iterm: looks like we need fix up XTVERSION, otherwise fine (does it not have its own `TERM` value, btw?)
* kitty/alacritty: look fine, assuming that's not the sixel-enabled alacritty
* Terminal.app: what the hell is going on here, gonna need to play with this, what a mess

so i mean there's a lot of messages about "invalid unicode", and a lot of missing glyphs, but that's because OS X is missing a bunch of unicode 13. i.e. displaying the absence of a glyph for those characters is the whole point of `notcurses-info`. it's supposed to show you how well or poorly your setup performs.

one real problem is that everything is showing support for quadrants, yet none of them seem to actually have working quadrants. that's something i'll need fix.

overall, though, i am quite heartened by this display.

**Comment by dankamongmen** [comment]
it looks like all kinds of backsplatter is coming out from Terminal.app; look at that `rgb` reply etc. gross. hrmmmm that's gonna be something of a pain in the ass to debug without an actual mac...BUT this is something where my old garbage mac ought work fine, right? it'll have terminal app, and i'd just need ssh into some other machine and run things, presumably?

**Comment by dankamongmen** [comment]
the iTerm2 XTVERSION error ought no longer be seen, and the terminal ought now be properly detected to be iTerm no matter your TERM variable (though you still want the latter to be correct).

**Comment by dankamongmen** [comment]
> one real problem is that everything is showing support for quadrants, yet none of them seem to actually have working quadrants. that's something i'll need fix.

belay this; the sextants are missing, not the quadrants. quadrants look fine, and thus this output is correct.

**Comment by michaelsbradleyjr** [comment]
iTerm2's FAQ has long recommended setting TERM to `xterm-256color`: https://iterm2.com/faq.html.

And that's how it's set in mine.

**Comment by michaelsbradleyjr** [comment]
> it'll have terminal app, and i'd just need ssh into some other machine and run things, presumably?

That should work, yes, good thinking. I don't know, though, how much Terminal.app has evolved over the years. I'm also not sure if iTerm2, etc. offer builds that will run on your old mac.

**Comment by dankamongmen** [comment]
> iTerm2's FAQ has long recommended setting TERM to `xterm-256color`: https://iterm2.com/faq.html.

good deal; i have updated `TERMINALS.md` with this information, thanks!

**Comment by dankamongmen** [comment]
> That should work, yes, good thinking. I don't know, though, how much Terminal.app has evolved over the years. I'm also not sure if iTerm2, etc. offer builds that will run on your old mac.

eh Terminal.App is the only one that looks like it needs immediate local tender loving coding. i'll take a look at it when i get back to the Danktower on Monday. i think i might rename this bug "iterm2 XTVERSION lexing is broken", and create a new issue for Terminal.app.
