### ISSUE TITLE
build a windows installer

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2071]
presumably an MSIX file. https://docs.microsoft.com/en-us/windows/msix/

this is necessary for getting into winget (#2070).

https://docs.microsoft.com/en-us/windows/msix/desktop/source-code-overview

i guess we probably need stick all our dependencies in there, as well? and we're just abandoning any attempt at using e.g. a system-wide ffmpeg? i think so, unless such a thing is available via winget. if it is, we should probably use that.

**Comment by WSLUser** [comment]
You can use an msi instead. I've seen plenty of those in winget too. But msix does provide the most security. However it does have one critical flaw: disconnected systems that install msix manually rather than through the MS Store are unable to activate due to an online verification failing. So msi might be a better choice.

**Comment by WSLUser** [comment]
As far as I'm aware, you still require WIX when building a MSI. Still, MSITools is interesting project and if it works without WIX, that probably would make it alot easier for you. People can always use WINE to emulate the windows binary of notcurses if needed for some windows TUI application that doesn't have a Linux equivalent.

**Comment by rgwood** [comment]
FWIW I would not recommend MSIX for this. It's got a lot of baggage related to the last decade of "modern Windows" attempts, and in my experience it's unreliable and poorly documented.

Most MSIX use is because it's a requirement in the Microsoft Store, but MS is dropping that requirement with Windows 11. It's very rare to see MSIX packages outside the Store (even for Microsoft software).

[Inno Setup](https://jrsoftware.org/isinfo.php) might be worth considering. It's rock-solid (VS Code uses it!) and pretty easy to script.

**Comment by dankamongmen** [comment]
> Most MSIX use is because it's a requirement in the Microsoft Store, but MS is dropping that requirement with Windows 11. It's very rare to see MSIX packages outside the Store (even for Microsoft software).

the microsoft store requirement was my entire reason for thinking MSIX the way to go, so this is a very relevant fact. thank you, kind stranger (i assume i've never met you, though if you're in vancouver, i thank you for goodly British Columbian herbs, the mainstay of my twenties)!

**Comment by dankamongmen** [comment]
![image](https://user-images.githubusercontent.com/143473/142795974-2fb8fc9b-74e6-4109-b4c8-dc727c8eaa33.png)

**Comment by dankamongmen** [comment]
![image](https://user-images.githubusercontent.com/143473/142796197-94b85f99-20a7-4777-8304-c0fbfa429833.png)

i do sometimes amaze even myself with my badassery

**Comment by dankamongmen** [comment]
missing icon in the add/remove programs view, yuck

**Comment by dankamongmen** [comment]
some problems:

* doesn't seem to support "upgrade" cleanly, where the previous version would be deleted
* do we really have to include all our dependent DLLs?
* we're going to need to set default paths based on install location choice; ought we use a registry key?

**Comment by dankamongmen** [comment]
we're using OpenImageIO instead of ffmpeg at the moment to work around #2355, but know that this requires about 40 extra DLL files, and blows up our installer/installed by about 200MB (from 50MB).

**Comment by dankamongmen** [comment]
expected default is...not what i would have expected

![image](https://user-images.githubusercontent.com/143473/142802370-b9121c5f-687a-4133-a01e-90b9e9e18a4f.png)

**Comment by dankamongmen** [comment]
so i made one, and submitted a winget package around it. we'll want to automate this process, but for now, i'm calling this done. yay!

**Comment by rgwood** [comment]
Amazing work, thanks!

**Comment by dankamongmen** [comment]
https://github.com/microsoft/winget-pkgs/pull/35791
