### ISSUE TITLE
out-of-plane cursor position

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2203]
I'm not sure whether this is a bug or intended behaviour. But after putting more text than fits in a scrolling plane, the cursor is placed outside of the plane. Trying to move the cursor to where it already is results in an error.

[I've created an example for this.](https://github.com/dankamongmen/libnotcurses-sys/blob/main/examples/issue-cursor-end-position.rs)
![image](https://user-images.githubusercontent.com/5832068/134645683-c35f9386-e4eb-4b20-8084-1ce93a7cbf03.png)

**Comment by dankamongmen** [comment]
intended behavior. do you feel something else ought happen?

the only difference i can seeing as being consistent with other stuff is if i allowed you to move there, but you then still woudln't be able to do anything useful there.

**Comment by dankamongmen** [comment]
reasoning:

* when you emit a cell, you *have* to move to where the next one will be printed. otherwise, you need an explicit move between every cell, madness
* on the last cell of the plane (technically the last cell of any row, unless scrolling is enabled for that plane), you must go somewhere, or else you'll keep printing over that last cell
* if you are scrolling in the plane, go to the next line's beginning, sure
* if you are not scrolling, then, we must go to a coordinate where we cannot emit cells, lest we *do* emit cells

so that kinda locks in behavior for cell emission. now on the move side:

* movement to an off-plane cell is almost certainly an error, since you can't do anything useful there
* we can either allow it (`ncplane_cursor_move_yx()` would then never return an error), or detect it and return an error
* unlike rust, in C you needn't act on an error, so only people interested in whether they succeeded need check
* returning the error thus loses no useful functionality, and allows an error to be detected, while costing nothing to people who don't care whether their programs work

so i think this will pretty much stand, unless you have an insight i've missed.

**Comment by dankamongmen** [comment]
note btw that for a plane with scrolling enabled, the semantics are aligned: an output will never take you outside the plane, and an explicit move won't, either. it's only without scrolling that there arises a differentiation.
