### ISSUE TITLE
notcurses-info "kbd+/-" not correct on latest master, on neither kitty nor foot

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#2412]
notcurses dae138c7d0e4c5d9a96e479b57209de0cfc560f4

`notcurses-info` reports `kbd-`, on both kitty-0.23.1, and foot master. That is, it doesn't recognize the kitty keyboard protocol is available. It _has_ enabled it however; upon exit, it's still enabled on kitty:

```sh
✓ daniel@mini ~% ~/src/notcurses/bld/debug/notcurses-info 
notcurses 2.4.99 on Kitty 0.23.1 (Linux 5.11.16-artix1-1)
64 rows (16px) 141 cols (8px) 1024x1128 rgb+256 colors
gcc-11.1.0 (LE)
terminfo 6.3.20211021 libdeflate 1.8 GPM n/a
avformat 58.76.100 avutil 56.70.100 swscale 5.9.100 avcodec 58.134.100
af+ ab+ sum- cup+ vpa+ hpa+ sgr0+ op+ fgop+ bgop+ bce-                          
bold+ ital+ struck+ ucurl+ uline+ u7+ ccc+ rgb+ el+                             
utf8+ 2x1+ 2x2+ 3x2+ 4x2+ img+ vid+ indn+ gpm- kbd-                             
default background 0x000000 considered transparent                              
1st gen rgba pixel animation support

✓ daniel@mini ~% echo -e '\e[?u'                         
✓ daniel@mini ~% 1u
```

**Comment by dankamongmen** [comment]
sacre bleu! great catch, thanks

**Comment by dankamongmen** [comment]
hrmmm this seems to happen sometimes but not all times; it always happens following a reset. ahhh i think i know what's up.

**Comment by dankamongmen** [comment]
ok, so `notcurses-info` sets `NOTCURSES_OPTIONS_DRAININPUT` (properly), indicating that it will not be reading input.

in such a case, we ought not send any keyboard modifiers. we hold true to htis for kitty. but we then base `XTMODKEYS` off simply whether or not we have a kitty keyboard level. we don't, so we send it. this approximates to `1u`, which is why subsequent `notcurses-info` launches *do* show the protocol.

so, i think the fix is twofold:
* even with DRAININPUT, send a *query* (not a set) for keyboard support level, so display is accurate
* with DRAININPUT, never send XTMODKEYS -- this should have always been happening

and that ought get this. thanks a lot for the good eyes!

**Comment by dankamongmen** [comment]
hrmmm that query's typically still going to come back with a kbdlevel of 0, though, and thus not show up as in use. i guess we'll need a sentinel.

**Comment by dankamongmen** [comment]
ok, the first part is in: we now never send keyboard modifiers with DRAININPUT. this applies to XTMODKEYS as well as kitty, and it applies when entering or leaving the alternate screen.

**Comment by dankamongmen** [comment]
alright, we're using `UINT_MAX` as a sentinel, and have expanded out `kittykbdsupport`, which we're now using in `notcurses-info`. and....as expected, everything now seems to work.

**Comment by dankamongmen** [comment]
oooh maybe not, hold off, still not seeing support in `foot`.

**Comment by dankamongmen** [comment]
ahhh, works once i updated my `foot`. fixed!

**Comment by dnkl** [comment]
Latest release still has no support. Master has level 1. Then there are PRs open to add more.

**Comment by dnkl** [comment]
Awesome! Thanks!

**Comment by dankamongmen** [comment]
> Latest release still has no support. Master has level 1. Then there are PRs open to add more.

yep, like i said, it worked as soon as i updated to current master. ok great, i'm really glad you caught this, thanks!
