### ISSUE TITLE
ncinput's evtype is NCTYPE_UNKNOWN for key presses in Kitty on macOS and Linux

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#2527]
I'm experiencing this with Notcurses v3.02 and v3.03, I haven't tried with other versions.

I would have have expected `NCTYPE_PRESS` instead for key presses, but maybe I have the wrong expectation.

For key releases I do see `NCTYPE_RELEASE`.

**Comment by dankamongmen** [comment]
this is working as i expect it to, but perhaps we can do better? i forget what happened here, but it does seem we ought be able to distinguish press from unknown. maybe not, though?

**Comment by dnkl** [comment]
From my own testing with `notcurses-input`, I believe you "require" the event sub-parameter to be `1` for it to count as a press:

```
CSI key-code             # this is a press event
CSI key-code;modifier    # this is a press event
CSI key-code;modifier:1  # this is a press event
CSI key-code;modifier:2  # this is a repeat event
CSI key-code;modifier:3  # this is a release event
```
But, kitty tries to be bandwidth efficient, and always uses the short form, where the sub-parameter is omitted (i.e. `CSI key-code;modifier`, instead of `CSI key-code;modifier:1`). notcurses appears to treat this as `unknown`.

I don't think it makes much sense to use `unknown` here. A missing sub-parameter should be treated as a press event.

FWIW: foot _does_ explicitly include the press/release sub-parameter for all event types, including presses. And here, notcurses **does not** report `unknown`.

**Comment by dankamongmen** [comment]
that's correct. and i agree, when i know that we're using the kitty protocol, lack of a modifier ought be considered a press.

**Comment by dankamongmen** [comment]
alright, i now treat definite `kitty_kbd` messages lacking an event type as PRESS.
