### ISSUE TITLE
update the ncpalette API

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2565]
right now we have these functions for setting / retrieving the rgb color:

- `ncpalette_get_rgb8`
- `ncpalette_set`
- `ncpalette_set_rgb8`

in order to make it more homogeneous with the rest of the API, I think we should add a new `ncpalette_get_rgb` function and rename `ncpalette_set` → `ncpalette_set_rgb` so it would be as follows:

- `ncpalette_get_rgb`
- `ncpalette_get_rgb8`
- `ncpalette_set_rgb`
- `ncpalette_set_rgb8`

**Comment by dankamongmen** [comment]
agreed with you on the desire for `ncpalette_get()`. regarding the rename, i don't know. void and opensuse are still back on pre-3.0 because of deps which need updating for the 3.0 name changes. i was rereading this the other day:

https://www.jwz.org/blog/2012/06/i-have-ported-xscreensaver-to-the-iphone/

and jwz's words struck me: "If there are old features that you would like to discourage the use of, then you mark them as obsolete -- but you do not remove them because thou shalt not break working code. If you don't agree with that, then please, get out of the software industry right now. Find another line of work. Please."

and i hate carrying around `__deprecated__` identifiers.

but definitely we'll add `ncpalette_get()`.

**Comment by joseluis** [comment]
ok! yeah, I agree that's fair enough :)

**Comment by dankamongmen** [comment]
added `ncpalette_get()`
