### ISSUE TITLE
New language wrapper

### ISSUE THREAD

**Issue by pepe** [dankamongmen/notcurses#729]
I want to wrap notcurses for the Janet programming language https://janet-lang.org, and I would like to ask, if you have some "essential" API I would need to start drawing in the terminal. I looked both at Python and Rust wrappers, but I am not very familiar with neither of them and feeling a little bit lost.

And truth to be said, I have only read the (very funny, yes) paper and looked a bit around the code in the repo.

If you find this question stupid, feel free to close it.

Again I have had a great time reading the paper. Thanks

**Comment by dankamongmen** [comment]
I'm delighted to hear of your interest. I assume by "the paper" you mean the Notcurses book? I'm glad you enjoyed it :).

I wouldn't likely want to keep the Janet wrappers in this repo, since I'm not personally familiar with the language, and I often have to patch up the C++/Python/Rust wrappers myself as I add new (or change) functionality. With the upcoming API freeze in Notcurses 2, though, that's less of a problem. I whole-heartedly encourage you putting them out.

As for the most central elements....the most fundamental aspects are likely something like:

* plane creation, plane text output, and cell construction, culminating in `ncplane_putc_yx()`. All the other `ncplane_*` functions are wrappers around `ncplane_putc_yx()`.
* visual creation and rendering, culminating in `ncvisual_render()`
* other ncplane functions
* miscellaneous (ncmetric, other stuff)

i hope that was informative!

**Comment by dankamongmen** [comment]
The thing to look at is notcurses.h, as what you really want is a wrapper for each of the functions there (and likely an implementation of all the `static inline` functions).

**Comment by pepe** [comment]
It is much more than I hoped! Thank you a lot.

Sorry for "the paper" it felt sciency to me a that confused my notion of it. It definitely is "the book". 

I've never thought about you adding Janet wrapper to your repo.

For my wrapper implementation: Janet has kind of OOP-like facilities with AbstractTypes wrapping the C code. So I guess I start with Plane and Cell abstractions. And I would like to target the 2.0 API.

Again thank you very much. I am impressed with your codes and attitudes. Stay safe.

**Comment by dankamongmen** [comment]
I really appreciate the sweet comments =]. While I don't necessarily want it in the main repo, I'll certainly provide a link to your project from the README, and if you maintain it assiduously for a release or two, I'd allow you to add it to the main repo and make you a co-maintainer (if you want).

If you're OOPish, @grendello 's C++ wrappers might be good to look at. My general strategy would be:

* one class per exported Notcurses C struct (notcurses, cell, ncplane, ncvisual, widgets...)
* minimize the amount of extra state you carry in your classes (ideally they would be stateless wrappers)
* ideally, i'd like both exceptionful and exceptionless behavior to be supported (it looks like Janet supports exceptions). if one or the other is too big a pain, no problem. since Janet doesn't look like a language geared towards high performance, just exceptions is probably fine. it's your call either way.
* Notcurses indicates errors via return code; make sure these are available (either as propagated return codes or as exceptions) to the user. not checking these codes is the #1 source of invalid bug reports.

Good luck! I look forward to seeing what you accomplish. Thanks for using Notcurses, and hack on =].

**Comment by dankamongmen** [comment]
Oh! Regarding the "2.0 API", it's no different from the current one. Just once I cut 2.0, it'll be frozen (well, much more frozen than it is now). Most everything is in its final form as of 1.5.2, though.

**Comment by pepe** [comment]
That CPP idea is what I wanted (without knowing it) the most. That footnote CPP joke was the best :)

To your points:
- yes one class per C struct + some helpers of assorted functionality 
- in Janet, there is usual to use one flag entry in AbstractType, but mostly for things Janet GC needs to know + state for Janet (initialised, closed etc.)
- I am using exceptions in Janet, so I guess my lib will do too
- usually, I am trying to return the "self" as it was custom in SmallTalk so that I will solve it through the exception, where it makes sense. I have seen some nc function returns the number of chars written, so there I will maybe return it too.

Thank you. I will try to deliver, as a father of three tho :-).

**Comment by dankamongmen** [comment]
No obligation, to be sure!

**Comment by pepe** [comment]
Hello. I have started with the wrapper at last :-). Little more than two years yet. And only the bare minimum is done, yet here it is https://git.sr.ht/~pepe/janet-curses-not.
