### ISSUE TITLE
no direct mode from Rust bindings

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#853]
I was trying to use the direct mode from Rust but it doesn't seem to be possible, since there are no bindings for it. Is that intentional? Thank you

**Comment by dankamongmen** [comment]
That should not be the case. I'm using bindgen-rs to automatically........OH RIGHT, you have to mention each header, don't you? And I separated them out recently. THANK YOU for pointing this out, my friend! I'll have this fixed up ASAP for 1.6.12/1.7.0.

**Comment by dankamongmen** [comment]
I can probably have this done within an hour or so if you're working off a git checkout. Otherwise, 1.6.12 ought be out by this weekend at the latest.

**Comment by joseluis** [comment]
Ok that's fantastic

**Comment by dankamongmen** [comment]
@joseluis , thanks so much for reporting this embarrassing oversight. I believe that the issue is rectified, though I am not yet any kind of Rust expert. I've added a very simple unit test for opening and closing direct mode to the `libnotcurses-sys` testing infrastructure.

Please don't hesitate to report any other problems you run into. This fix will be present in 1.6.12/1.7.0.

**Comment by joseluis** [comment]
Yes, it seems it works well now! Thank you for the speedy fixin'

**Comment by dankamongmen** [comment]
> Yes, it seems it works well now! Thank you for the speedy fixin'

thanks for the confirmation! i will be getting to your other issues tonight; work has me workin' at the moment
