### ISSUE TITLE
rust: Missing channels API

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#858]
In [notcurses_channels(3)](https://nick-black.com/notcurses/notcurses_channels.3.html), and in [USAGE.md](https://github.com/dankamongmen/notcurses/blob/master/USAGE.md#channels) are listed a series of functions which doesn't appear in the Rust bindings, nor they appear in the doxygen documentation.

And they are also employed in sevearl examples in the pdf manual, so I'm guessing they should be readily available.

**Comment by dankamongmen** [comment]
Yeah we're gonna have a lot of these, basically anything where the C API is expressed as `static inline`s. I've got a bug on handling this in a general way #800. Though for things which are simple enough, I'd prefer to express them in the native language in the wrapper itself, as I've done with one or two functions already.

If you're an experienced Rustacean and would like to submit PRs, I'll take them with thanks and good cheer. Otherwise, I'm thinking I'll probably go ahead and drop a compiled version of each `static inline` into the actual shared object, to get them all in one fell swoop.

Keep these coming -- they're valid bugs, not duplicates of #800. I consider this bug to be looking for a pure Rust implementation of these bit-twiddling functions in `libnotcurses-sys`. Do you agree, @joseluis ?

**Comment by joseluis** [comment]
Well, I'm not *very* experienced yet, I'm learning Rust as I go (among many other things... da-da-da... jack of all trades). But I do love Rust as a language and my intention is to keep using it for everything I can for at least the next 50 years :)

It think it's probably a good idea to tell you now I'm developing a safe rust wrapper library around your rust bindings, and that's why I'm finding so many bugs... I'm combing your lib as I'm learning it and wrapping it.

Your library is exactly what I've been waiting for for my TUIs, and once I finish the wrapper I'd like to publish it. I can invite you to my repo if you want to see what I'm doing, and feel free to open some issues, ask or suggest whatever.

It's funny that until now I didn't understand why you decided to put those 4 wrapper functions in the notcurses crate. Now I see. Although I'm not even using those, since I'm directly wrapping all the libnotcurses-sys unsafe bindings in a globally consistent way, around safe structs and such... and didn't feel the need for them.

But regarding those static inline functions, I agree with you that it's probably the best idea to recreate them in Rust in the notcurses crate, with the [`#[inline]` attribute](https://doc.rust-lang.org/reference/attributes/codegen.html?highlight=inline#the-inline-attribute) even so that they can be inlined too. Yep. And in my lib I'll do the safe wrappings.

I'll see what I can put together this week.
