### ISSUE TITLE
errorless channel_set

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#876]
Hi @dankamongmen I hope you like what I did here with the reimplementation of the `channel_set()` function. https://github.com/dankamongmen/notcurses/commit/dbec390facea2834aa6550a2899d7a74a6875396

I think we don't loose anything by masking the passed rgb value rather than returning an error when the last bits are dirty, am I right? And it should run faster without the conditional branching, and the subsequent error checking on user's code.

I want to do a similar thing with `channel_set_alpha()`, but first I wanted to check with you.

**Comment by dankamongmen** [comment]
The reason I return an error is because otherwise arithmetic bugs on rgb are silent.

Imagine I have the following loop (not tested, forgive unintended errors):

```
for(unsigned v = 0 ; v < 256 ; ++v){
  channels_set(&chan, 0x10000ul * v + 0x100ul * v +  v);
}
```

i'm probably trying to progressively brighten a black/grey/white color, right? but i actually have a bug--it's 0..255, not 0..256, and when i hit tte last case, i'm going to get 0x1010100, a not-quite-black but definitely not the brilliant white we presumably intended.

if someone want to get masked values, that's why the `_clipped()` versions (returning void) exist. if we're missing a `_clipped()` in terms of orthogonality somewhere, let's add it. i've simply been bit too many times by passing over/underflows into rgb constructors.

**Comment by dankamongmen** [comment]
with that said, if this is somehow contrary to rust idiom, feel free to go with your heart. but they'll be staying as they are in the innermost c.

**Comment by joseluis** [comment]
I feel you, and I do agree that leaving those in C is wise. Same with the `_clipped()` versions.

Still I would really like to remove them from the Rust bindings. Since these functionas are manually implemented they don't use unsafe, and I'm able to choose the types carefully so we can leverage the strong type checking guarantees. E.g. all those overflowing problems would be catched by the compiler since the RGB components are u8, which a user of the library is forced to use (unless he uses unsafe to subvert the guarantees but that's his problem not ours).

And we have the associated unit tests that, if we want, can test for resiliance in the face of bad input data and things like that.

**Comment by dankamongmen** [comment]
I'm not worried about resilience in the face of bad data, so much as programmer error leading them to gnash their teeth and render their sackclothes and scrape themselves with broken pottery and lament, "why won't you think of us nick black there is no 0x100 green value why hast thou forsaken me?"

do the rust as you wish, presumably dropping the `_clipped` variants if you go this way.

**Comment by dankamongmen** [comment]
i mean obviously i am worried about resilience in the face of bad data, lest someone quote me otherwise in a senate hearing one day

**Comment by dankamongmen** [comment]
So I think we can call this cool? You can remove them from the Rust bindings, and just not wrap the `_clipped` forms? If so, I'm closing this. Feel free to reopen if further discussion/work is warranted.
