### ISSUE TITLE
Maybe create a list of recently updated functions?

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#905]
It just occured to me that it would be useful to have a manually updated list of recently modified static inline functions, in order to help keeping track of when it may be necessary to review those manually re-implemented bindings...

For example I had already copied out the static inline cell functions a week ago in order to have them at hand for when I got to actually implement them. Today I thought that after the work you did last week I better play safe and copy them again. It turns out 9 functions had important inner changes and 1 of them got removed.

If I had implemented them last week, they would no longer work well, and they'd be difficult to debug.

Another option would be for you to make an annotation in the corresponding rust inline function that it needs to be reviewed/updated.

What do you think would be the best approach to maintain these bindings?

**Comment by dankamongmen** [comment]
I'm trying to kinda do this with NEWS.md. I agree that this will be a problem as the bindings expand in power and coverage. Let me consider what can be done.

**Comment by joseluis** [comment]
I've cleaned it a bit more, put them in a single folder in order to make it less of a mess, and added an example output of the `generate` command.

And it just occured to me that it may be a good idea to transform it into a practical example of the rust bindings, employing direct mode and/or full mode. And make it a tool for monitoring changes to the functions reimplemented manually too.

I already wanted  to experiment with parsers and substituting shellscript for Rust at some point, so I may as well kill 3 birds with this stone.

**Comment by dankamongmen** [comment]
ok, this issue has been open for a minute, and here's my central thought:

when i add a public function, i currently have to edit, at a minimum, six files:
 * implementation
 * header
 * NEWS
 * USAGE
 * man page
 * python bindings

a seventh file might cause me to hurl myself beneath a train. thankfully, the visible API change is shrinking to epsilon, no? so we shouldn't have nearly as much churn here going forward.

i'm closing this as a NONFIX because my soul simply can't bear the idea of yet another place i have to edit. if it causes problems going forward, we can reconsider this.
