### ISSUE TITLE
replace "simple" with "char" or something in API

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#912]
I guess it just load a cell with a simple character, But why does it return 1?

And isn't it related to the now defunct cell_simple_p?

```
static inline int                                                                                                       
cell_load_simple(struct ncplane* n, cell* c, char ch){                                                                  
  cell_release(n, c);                                                                                                   
  c->channels &= ~(CELL_WIDEASIAN_MASK | CELL_NOBACKGROUND_MASK);                                                       
  c->gcluster = ch;                                                                                                     
  return 1;                                                                                                             
}
```

**Comment by dankamongmen** [comment]
The term is overloaded. I ought rename this `cell_load_char()` in a perfect world. Perhaps I will do so. The only problem there (besides API churn, but that boat has sailed) is that "char" is also a fairly overloaded term. From the Notcurses book:

![2020-08-17-181234_797x669_scrot](https://user-images.githubusercontent.com/143473/90449356-40422300-e0b5-11ea-9b68-165ab9cdf1a6.png)

So:

* the (foolishly user-exposed) term "simple" once meant "ASCII character", which means "`char n, 0 <= n < 128`"
* it now means "single Unicode", and that meaning is no longer user-exposed
* the overloaded sense  (`char`) is still being referred to as `simple`

So it **was** related to `cell_simple_p()`, but no longer is. It is now simply a way to get a pure `char` into a `cell` (you'd otherwise need NUL-terminate it and use a `char *`). It thus ought be renamed `cell_load_c()` if we're going by `ncplane_putwc()`, but we already have `ncplane_putc()`...referring to `cell`s. ugh.

either way, I probably ought add a `wchar_t` form of whatever i rename this to.

leaving this open for potential rename/addition of `wchar_t` form, but hopefully that answers your questions. a bit of a naming shitshow here, sorry; this was some of the very first code written for notcurses.

**Comment by dankamongmen** [comment]
`cell_load_char` is better than `cell_load_simple`, for sure. we IMHO either ought go to:

`cell_load_char()` + `cell_load_wchar()`, or `cell_load_ascii()` + `cell_load_ucs32()`

**Comment by dankamongmen** [comment]
Note that if we rename these, we probably want to rename `ncplane_putsimple_*()` as well. Note that any such renaming will suddenly make `ncplane_putwc_*()` weirdly-named, so it would call for a rename there, too.

Beginning to be a good bit of churn :/.

**Comment by joseluis** [comment]
This time before 2.0 lends itself into doing this kind of global coherent renaming. Maybe a spreadhseet would be good for the design overview.

**Comment by dankamongmen** [comment]
@joseluis , you've learned a lot in two weeks since filing this. Any idea on desirable nomenclature? @grendello ?

**Comment by joseluis** [comment]
Char is better yeah
