### ISSUE TITLE
channels_blend() is a secret to everybody

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#917]
E.g. used in:
```C
// Returns the result of blending two channels. 'blends' indicates how heavily
// 'c1' ought be weighed. If 'blends' is 0, 'c1' will be entirely replaced by
// 'c2'. If 'c1' is otherwise the default color, 'c1' will not be touched,
// since we can't blend default colors. Likewise, if 'c2' is a default color,
// it will not be used (unless 'blends' is 0).
//
// Palette-indexed colors do not blend. Do not pass me palette-indexed channels!
static inline unsigned
channels_blend(unsigned c1, unsigned c2, unsigned* blends){
// ...
}
```
What are the constraints? What's its maximum value? Is it used in more places? I see it also in `blit.c` and `render.c` but is it the same type everywhere sharing the same constrainst?

**Comment by dankamongmen** [comment]
https://nick-black.com/dankwiki/index.php?title=Notcurses#Transparency.2FContrasting could probably stand to be integrated into the codebase.

**Comment by dankamongmen** [comment]
* `OPAQUE` indicates arrival at a solution for the channel (the channel can otherwise be solved only by reaching the bottommost plane without a solution)
* `TRANSPARENT` indicates no contribution to a solution for the channel
* `BLEND` indicates that the channel's solution is the average of subsequent `BLEND` cell channels (and/or the first `OPAQUE` cell channel) until the channel is otherwise solved

`BLEND 0xffffff` with nothing underneath it yields 0xffffff
`BLEND 0xffffff` with `OPAQUE 0x000000` underneath it yields 0x808080 (or maybe 0x7f7f7f)
`BLEND 0x606060` with `BLEND 0x202020` with `TRANSPARENT 0xffffff` with `OPAQUE 0x404040` yields 0x404040

**Comment by dankamongmen** [comment]
from the book:

![2020-08-18-081756_806x555_scrot](https://user-images.githubusercontent.com/143473/90511984-57bbf300-e12b-11ea-9712-d6c5bffac82b.png)

**Comment by dankamongmen** [comment]
> What are the constraints? What's its maximum value? Is it used in more places? I see it also in `blit.c` and `render.c` but is it the same type everywhere sharing the same constrainst?

constraints: `// Palette-indexed colors do not blend. Do not pass me palette-indexed channels!`. otherwise any valid RGB/default color, subject to mentioned interactions. the number of blends will be equal to the number of blend operations (it is used as the denominator for the final division)

maximum value: numeric limits

where used: primarily in `paint()` within the rendering core. it's only exposed to users as a convenience function. perhaps it oughtn't be.

constraints are the same for everyone.

**Comment by dankamongmen** [comment]
`'blends' indicates how heavily 'c1' ought be weighed. `

this somewhat cryptic wording is due to us doing the division in each call. i experimented with keeping a sum and reducing this to a single division at the end, but it never quite yielded results: https://github.com/dankamongmen/notcurses/issues/596

**Comment by dankamongmen** [comment]
> `'blends' indicates how heavily 'c1' ought be weighed. `
> 
> this somewhat cryptic wording is due to us doing the division in each call. i experimented with keeping a sum and reducing this to a single division at the end, but it never quite yielded results: #596

note that #914 stands a good chance of *actually* cutting down the time spent in this function, by improving cache behavior of the rendering loop. i have big hopes for #914.

**Comment by joseluis** [comment]
So  `blend` is an 8-bit value then, correct?

**Comment by dankamongmen** [comment]
> So `blend` is an 8-bit value then, correct?

blend could be up through `UINT_MAX`, but such a value is very unlikely in practice. it is the number of cells which have been blended while solving for this cell's render. it is dynamically bounded (but only indirectly) by the total number of planes.

**Comment by dankamongmen** [comment]
> > So `blend` is an 8-bit value then, correct?
> 
> blend could be up through `UINT_MAX`, but such a value is very unlikely in practice. it is the number of cells which have been blended while solving for this cell's render. it is dynamically bounded (but only indirectly) by the total number of planes.

while values greater than 256 are likely to be counterproductive or at the very least pathologically ill-conceived, they must be supported.

**Comment by joseluis** [comment]
aah, ok sorry now I see. Ok I'll use u32 then...

**Comment by dankamongmen** [comment]
> aah, ok sorry now I see. Ok I'll use u32 then...

is there any Rust equivalent of C's `unsigned` (i.e., implementation-dependent, subject to constraints?). technically it's a u64 on implementations with 64-bit `unsigned` (and u16 for the obvious alternative), though only at the ABI level. if we needn't worry about that, `u32` or even `u16` (if there's a reason to choose `u16`) are satisfactory. the API as defined in C only guarantees 16 bits here, because that's the minimum size of `unsigned`.

**Comment by dankamongmen** [comment]
I'm honestly thinking this maybe doesn't need exposure. If a user wants to calculate an average, they have many ways to do that. I just don't see them needing to do what's really a pretty render-specific operation.

hrmmm let me see if it's used in any demo code.

**Comment by dankamongmen** [comment]
> I'm honestly thinking this maybe doesn't need exposure. If a user wants to calculate an average, they have many ways to do that. I just don't see them needing to do what's really a pretty render-specific operation.
> 
> hrmmm let me see if it's used in any demo code.

```
I'm honestly thinking this maybe doesn't need exposure. If a user wants to calculate an average, they have many ways to do that. I just don't see them needing to do what's really a pretty render-specific operation.

hrmmm let me see if it's used in any demo code.
```

yeah i'm sorely tempted to claw this one back

**Comment by dankamongmen** [comment]
@joseluis you've convinced me that this function is more confusion than added value. add to that its crass lack of namespace-via-prefix, and `channels_blend()`, i hear Allah calling you home.

**Comment by joseluis** [comment]
Really? Is not going to be useful? I just finished reimplementing it :P Maybe I'll use it in the higher bindings, I'll see.

Then it must be the same case for `cell_blend_fchannel` and `cell_blend_bchannel` since they depend on that function.

Those were the last cell functions for me to reimplement...

**Comment by dankamongmen** [comment]
> Really? Is not going to be useful? I just finished reimplementing it :P Maybe I'll use it in the higher bindings, I'll see.
> 
> Then it must be the same case for `cell_blend_fchannel` and `cell_blend_bchannel` since they depend on that function.
> 
> Those were the last cell functions for me to reimplement...


I know, I'm sorry man :(. But your questions made it clear that:

* this function isn't easily explained (because it's so tightly tied to our rendering process, not a general thing), and
* all it accomplished was the world's most confusing average

so yeah, it has to go. sorry for the wasted work @joseluis. i will cheer for Barcelona FC as i make my next commit, in penance.

**Comment by dankamongmen** [comment]
hrmm i had meant to put that up for a PR, but fire in the hole!

https://www.youtube.com/watch?v=f96p-IhcZhQ

**Comment by joseluis** [comment]
Don't worry, not a big deal and not really wasted work, in fact needed in order to realize what's useful and what's not. Thanks for the detailed explanation.

BTW take a look to https://github.com/dankamongmen/notcurses/issues/911#issuecomment-675444367 and we can leave this issue behind us. Although now is not as relevant since is only used internally, I'm curious if you agree with me in principle regarding the mutability of the first channel...

**Comment by dankamongmen** [comment]
Whilst smoking a Newport short today, I realized why this had ever been exposed: the unit tests don't link unexposed functions. this was never intended for public consumption. nowadays we have `internal.h` but in those early dawn of man days we were living without the niceties of multiple header files, and all was Void
