### ISSUE TITLE
About receiving "cells" as u64, u32 & cell

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#920]
Why does `ncplane_gradient` receives `ul`, `ur`, `ll` & `lr` as u64 while `ncplane_highgradient` receives them as u32? Couldn't they be unified?

And how are those parameters related with cell structures received using the same names in e.g. `ncplane_box_sized`?

**Comment by joseluis** [comment]
There's an apparent conflict in function `ncplane_highgradient_sized` that I'm recreating in Rust.

That function has to receive them in principle as u64, since it calls `ncplane_gradient_sized` which receives them as u64, but then it calls `ncplane_highgradient` which receives them as u32, so I have to try to cast them, and if I do it safely (that's the point after all), it will panic if the value doesn't fit...

Ideally they all could be u32... 🤞

**Comment by dankamongmen** [comment]
looking into this; these functions can very likely use some love. as soon as something exceeds 4 arguments or so, i tend to look at it as irredeemably corrupted, lol. btw i cannot thank you enough for the detailed, rigorous review of all this crap. your observations have generally been spot-on.

**Comment by dankamongmen** [comment]
also i might move 1.7.0 back a bit, as you're finding a lot of issues, and i want to get them right. those delivery dates are entirely arbitrary.

**Comment by dankamongmen** [comment]
ok, i see the confusion. this is not very obvious.

`ncplane_highgradient` gets its higher resolution by using half blocks, which effectively doubles your vertical resolution in terms of characters. "using half blocks" in this or other contexts means "treating cells as two pixels" (remember, a cell has two colors -- foreground and background -- whereas a pixel has only one). `highgradient` is essentially dealing with a 2*rows X columns display of pixels. this restricts it to using the HALF BLOCK glyph.

`gradient` and `gradient_sized` can use any EGC. it's most obvious to consider using them with FULL BLOCK, but you can absolutely use 'A' or whatever. in this case, there are two independent colors in every cell -- a foreground and a background. you can apply a gradient on both channels (varying f + b across ul, ur, ll, lr) or only one (varying f + constant b, or vice versa).

i.e. you could have a screen of As where the As are getting lighter from left to right, and your background is getting darker from left to right. that makes sense?

`highgradient` has no possibility for this, because there is only one EGC being used, and it has symmetry across the horizontal axis, and there is no "background" -- there is, but it's integrated into the one possible gradient.

that's the story. let me now look into this 32-vs-64 business in the call chain.

**Comment by joseluis** [comment]
Ok, I'm not in a hurry for release. I'm also trying to get it right.

Just remember that if you make changes to the static functions please leave those annotated somewhere known so it's clear which ones I have to review.

**Comment by dankamongmen** [comment]
ideally you could write `ncplane_highgradient` in terms of `ncplane_gradient`, but alas, i do not believe it to be possible, nor can i imagine a usefully generalized `ncplane_gradient` that would encompass this ability

**Comment by dankamongmen** [comment]
i.e. with `ncplane_gradient` you could set EGC=HALFBLOCK, and vary both f and b, but you'd only end up with a set of horizontal striations, not a true high-resolution gradient

**Comment by joseluis** [comment]
My most urgent concern right now is to know what should I do in `ncplane_highgradient_sized`. Whether I receive u32 and upcast to u64 for `ncplane_gradient_sized`, or receive u64 and downcast to u32 for `ncplane_highgradient`... which is *unsafer*.

**Comment by dankamongmen** [comment]
i just committed a new PoC, `gradients`, that makes these cases manifest. so the main issue here is `ncplane_highgradient_sized()` calling `ncplane_gradient_sized()`, right? got it.

i am wondering if the best thing to do here might be to induct `ncplane_highgradient_sized()` behind the veil of sleep, where i can freely cast as Kernighan intended. it's not like this function is called a lot and needs the `inline` boost. that ought neatly remove the problem from your purview. or do you see something truly unholy (as opposed to merely untoward) about what i'm doing?

**Comment by joseluis** [comment]
Well.. until I use those functions I don't really have an opinion on them... I was focusing on completing the bindings... Nothing that I see as unholy... except the many arguments and the pointer arithmetic... but I planned to cleanly wrap those so...

My main concern is to have underlying type contradictions and wobbly definitions of types that can come back later to bite us.

And now after the last commits, I think it'd be a good idea for me continue giving some love to the high level wrappers, create more examples/tests and see the problems/bugs I encounter while trying to do things...

In the back of my mind I suspect I'm gonna find things on the direct mode cursor... I want to try to test text, positioning, effects, and such but I'll open issues when due.

**Comment by dankamongmen** [comment]
> In the back of my mind I suspect I'm gonna find things on the direct mode cursor... I want to try to test text, positioning, effects, and such but I'll open issues when due.

the direct mode cursor stuff is probably the most unholy code in notcurses, as apparently you've picked up. it has to have a dialogue with the terminal, whereas normally we can just yell at it. i have very real concerns that e.g. user input can be interleaved with terminal replies. i also lie awake at night wondering what happens if we have a full input buffer when the terminal tries to reply. #784 hopes to partially address this.

**Comment by dankamongmen** [comment]
wait why is `ncplane_highgradient_sized()` documented in certain places as accepting `uint64_t`s, when it accepts `uint32_t`s? weird.
