### ISSUE TITLE
good info regarding strings and more in C vs Rust

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#923]
https://locka99.gitbooks.io/a-guide-to-porting-c-to-rust/content/features_of_rust/strings.html

I found this very good piece of info, when I was trying to decide how to deal with the functions accepting wide characters, and I decided they're not gonna be necessary for Rust after all, since the String (&str) type is pervasive and deals just with utf-8...  And I shivered when I found out the wchar_t type can be either UTF-16 or UTF-32 :S

> wchar_t type can be either 2 or 4 bytes wide and is a compiler / platform specific decision

EDIT: And I also leave [r4cppp](https://github.com/nrc/r4cppp) in case you want more bites of the apple... I mean of the crab... :P

**Comment by dankamongmen** [comment]
not only "can be", but "is" on at least windows and freebsd :/ i only have `wchar_t` interfaces because one must deal with `wchar_t` for certain standard library functions. it ought be banished to the land of wind and ghosts. internally i pretty much always use `char32_t` for UCS-4/UTF-32 and your friend and mine `char*` (perhaps `unsigned char*` soon) for UTF-8.

i think the string handling is all proper, but let me know if you find issues. use utf-8 unless there are compelling reasons not to, which i can't imagine you'll run into.
