### ISSUE TITLE
direct mode: screen doesn't update until printing a newline

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#926]
Ok, first direct-mode issue ;)

I just updated an [example](https://github.com/dankamongmen/notcurses/blob/ed748a516221c40227895280f0eec30fd99f63a7/rust/examples/direct-cursor.rs) that shows it with long enough pauses.

**Comment by dankamongmen** [comment]
This almost certainly has to do with stdio buffering. I'll look into it shortly. Thanks for the report!

**Comment by dankamongmen** [comment]
Yeah, `ncdirect_putstr()`, much like `puts(3)`, doesn't have a built-in flush of stdout. Since you're running it on the terminal, you've got default line-buffering going on, and it won't update (if you had redirected to a file, you wouldn't even get that -- you'd get flushes after 4KB (or some similar value, maybe 512), because that uses block buffering).

Does rust flush after every I/O? If anyone ever (foolishly, admittedly) iterates over a string calling puts() on each character or whatnot, they're going to have a really bad time.

I can add a comment to ncdirect_putstr() making it clear that it doesn't flush, but I'm not comfortable flushing every time it's called. That'll **kill** performance relative to the current if you're ever redirected to a pipe/file.

A few `ncdirect()` functions do flush:

`ncdirect_clear()`
`ncdirect_cursor_enable()`
`ncdirect_cursor_disable()`
`ncdirect_stop()`

but generally we don't want to flush. Let the user do that, if desired.
