### ISSUE TITLE
website typo

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#946]
In https://nick-black.com/notcurses/ `notcurses_cell—runtime capability detection` should be `notcurses_capabilities—runtime capability detection`

And may be good to add the info outlined in: https://github.com/dankamongmen/notcurses/issues/943#issuecomment-678802543 to https://nick-black.com/notcurses/notcurses_stop.3.html

**Comment by dankamongmen** [comment]
hrmmm, i mainly edit my wiki via https://www.mediawiki.org/wiki/Git-remote-mediawiki. i wonder if i can usefully pull it in as a submodule and somehow patch up authorization so that access here means access there, without access here meaning access to all my preciouses wiki. i will idly ponder it in the shower sometime.

oh shit wait that's not even the damn wiki. that's just the `index.html` from `doc/man`.

bah looking at this reminds me that i need to get rid of `notcurses_error`, an idea that never took off, and is now used in i think exactly two functions.

this error has been fixed; thanks for the report. it was not repeated in the page itself; i checked.

wait does https://nick-black.com/notcurses/ not 301 you over to https://notcurses.com? augh, it doesn't! ugh. that needs fixing.

the documentation is too damn scattered, ugh. for that matter, the book is pretty much completely obsolete after about chapter 8. i wrote it in march. ugh. augh. i think i might need a day of no notcurses pretty shortly here.

**Comment by dankamongmen** [comment]
Corrected index.html has been pushed to https://notcurses.com/

**Comment by dankamongmen** [comment]
* [ ] ~fix typo in index.html, push to qemfd.net:/var/www/notcurses~
* [ ] move /var/www/notcurses to /opt/notcurses, update apache virtualserver spec
* [ ] add 301 from nick-black.com/notcurses/{} to notcurses.com/{} for great SEO justice
* [ ] ~make bug about nc_err_t~ #948 
* [ ] travel back in time, eliminate guido van rossum, or at least convince him to take up professional lacrosse

**Comment by dankamongmen** [comment]
```
[schwarzgerat](0) $ curl https://nick-black.com/notcurses
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://notcurses.com/">here</a>.</p>
<hr>
<address>Apache/2.4.46 (Debian) Server at nick-black.com Port 443</address>
</body></html>
[schwarzgerat](0) $ curl https://nick-black.com/notcurses/index.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://notcurses.com//index.html">here</a>.</p>
<hr>
<address>Apache/2.4.46 (Debian) Server at nick-black.com Port 443</address>
</body></html>
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
https://www.youtube.com/watch?v=aVcStRyWdHM
